

function Head(){
  return (
   <>
     <title>Learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
   </>
  )
}


export default Head;
