

export const LukesPhrasal:{
   word: string;
   czWord: string;
  }[] = [
    {word: "	Be about to", czWord: "	 chystat se"},
{word: "	Be back", czWord: "	 vrátit se, být zpátky"},
{word: "	Be into", czWord: "	 zajímat se o něco (více než obvykle)"},
{word: "	Be up", czWord: "	 být vzhůru"},
{word: "	Break into", czWord: "	 vloupat se"},
{word: "	Break off", czWord: "	 přerušit činnost"},
{word: "	Break out", czWord: "	 vypuknout (kytky)"},
{word: "	Bring back", czWord: "	 připomenout"},
{word: "	Bring in", czWord: "	 vytvářet zisk"},
{word: "	Bring up", czWord: "	 zmínit něco, vychovávat"},
{word: "	Bring on", czWord: "	 způsobit, že se něco stane (často něco negativního)"},
{word: "	Bring it on", czWord: "	 příjmout výzvu"},
{word: "	Call on", czWord: "	 navštívit někoho, využít znalostí někoho nebo něčeho"},
{word: "	Call off", czWord: "	 vypnout něco"},
{word: "	Calm down", czWord: "	 uklidnit se"},
{word: "	Cheer on", czWord: "	 povzbuzení někoho, podpora někoho"},
{word: "	Cheer up", czWord: "	 povzbuzení někoho (hlavně pro někoho, kdo vypadá smutně)"},
{word: "	Come up (with something)", czWord: "	 přemýšlet o nápadu"},
{word: "	Come back", czWord: "	 vrátit se"},
{word: "	Come over", czWord: "	 navštívit"},
{word: "	Come along", czWord: "	 přidat se k někomu"},
{word: "	Come across", czWord: "	 potkat někoho náhodou"},
{word: "	Come in", czWord: "	 vstoupit"},
{word: "	Come across", czWord: "	 potkat náhodou, narazit"},
{word: "	Come forward", czWord: "	 informovat o něčem (dobrovolně  například o zločinu)"},
{word: "	Cut down", czWord: "	 zredukovat"},
{word: "	Cut off", czWord: "	 přerušit, zastavit (případně odříznout)"},
{word: "	Cut (it) out", czWord: "	 zastavit (to)"},
{word: "	Cut in", czWord: "	 přerušit někoho, když mluví"},
{word: "	Do up", czWord: "	 zapnout, zavázat (ohledně oblečení)"},
{word: "	Do with", czWord: "	 mít něco společného"},
{word: "	Do without", czWord: "	 obejít se bez něčeho, nepotřebovat"},
{word: "	Drop by", czWord: "	 navštívit na krátkou dobu"},
{word: "	Drop in", czWord: "	 navštívit na krátkou dobu"},
{word: "	Drop off", czWord: "	 ponechat někoho nebo něco na svém místě"},
{word: "	Eat up", czWord: "	 dojíst"},
{word: "	Fall apart", czWord: "	 zlomit nebo rozbít na kusy (neplatí pouze pro fyzické věci, ale lze použít například i pro rozbití přátelství)"},
{word: "	Fall down", czWord: "	 spadnout na zem (ve většině případů náhodou)"},
{word: "	Fill (someone) in", czWord: "	 říct někomu podrobnosti o něčem"},
{word: "	Fill up", czWord: "	 naplnit něco (úplně naplnit)"},

{word: "	Get away", czWord: "	 uniknout"},
{word: "	Get around", czWord: "	 řišit problém tím, že se vyhýbáte hlavnímu problému"},
{word: "	Get along (with)", czWord: "	 mít přátelský vztah s někým"},
{word: "	Get off", czWord: "	 vystoupit (často z dopravního prostředku)"},
{word: "	Get on", czWord: "	 nastoupit (do dopravního prostředku)"},
{word: "	Get up", czWord: "	 probudit se, vstát"},
{word: "	Get to (somebody)", czWord: "	 rozčílit někoho"},
{word: "	Get back to", czWord: "	 vrátit se k někomu nebo k něčemu"},
{word: "	Get back at", czWord: "	 pomstít se někomu"},
{word: "	Give away", czWord: "	 prozradit něco"},
{word: "	Give out", czWord: "	 přestat pracovat, přestat něco distribuovat"},
{word: "	Give in", czWord: "	 vzdát něco (z důvodu náročnosti)"},
{word: "	Give up", czWord: "	 přestat zkoušet, vzdát se"},
{word: "	Go out (with)", czWord: "	 jít s někým ven (většinou na rande)"},
{word: "	Go ahead", czWord: "	 jít k někomu pro povolení něco udělat"},
{word: "	Go up", czWord: "	 zvýšit se, vzrůst"},
{word: "	Grow up", czWord: "	 vyrůst, (lze použít i pro výzvu, aby se někdo přestal chovat dětinsky)"},
{word: "	Grow apart", czWord: "	 udržovat si vzdálenost od někoho"},
{word: "	Hand down", czWord: "	 odkázat, předat"},
{word: "	Hand in", czWord: "	 odevzdat"},
{word: "	Hand out", czWord: "	 rozdat"},
{word: "	Hang on", czWord: "	 držet něco, pověsit něco"},
{word: "	Hang out", czWord: "	 trávit s někým čas (chodívat s někým ven)"},
{word: "	Hang up", czWord: "	 ukončit hovor (dříve, než to čeká ten na druhé straně)"},
{word: "	Hold on", czWord: "	 držet něco pevně, žádost někoho aby počkal"},
{word: "	Hold back", czWord: "	 zabránit někomu nebo něčemu (předejít tomu, aby někdo něco udělal nebo řekl)"},
{word: "	Check in", czWord: "	 přihlásit se k odletu, odbavit"},
{word: "	Check on", czWord: "	 zkontrolovat"},
{word: "	Check up on", czWord: "	 vyšetřovat"},
{word: "	Let down", czWord: "	 zklamat"},
{word: "	Log in (to)", czWord: "	 příhlásit se na počítači k účtu nebo programu"},
{word: "	Log out", czWord: "	 odhlásit se od počítače nebo od účtu"},
{word: "	Log off", czWord: "	 odhlásit se od počítače nebo od účtu"},
{word: "	Look into", czWord: "	 prošetřit"},
{word: "	Look up", czWord: "	 zkontrolovat význam něčeho"},
{word: "	Look out", czWord: "	 dávat pozor na něco"},

{word: "	Make after", czWord: "	 honit někoho (například policie zločince)"},
{word: "	Make out", czWord: "	 rozluštit (šifru), nalíčit se,"},
{word: "	Make up", czWord: "	 vymyslet si (například příběh)"},
{word: "	Make up for", czWord: "	 vynahradit"},
{word: "	Pay back", czWord: "	 zaplatit zpět"},
{word: "	Pay for", czWord: "	 zaplatit za, dát někomu peníze za něco"},
{word: "	Pull down", czWord: "	 stáhnout něco"},
{word: "	Pull in", czWord: "	 přitahovat"},
{word: "	Pull through", czWord: "	 přežít"},
{word: "	Put down", czWord: "	 ponožovat někoho"},
{word: "	Put out", czWord: "	 uhasit požár, podráždit někoho žádostí o laskavost"},
{word: "	Put on", czWord: "	 vzít si na sebe šaty (ale i třeba rtěnku), přibrat na váze"},
{word: "	Put off", czWord: "	 odložit (termín)"},
{word: "	Put out", czWord: "	 uhasit"},
{word: "	Put up", czWord: "	 poskytnout finanční částku"},
{word: "	Rush into", czWord: "	 udělat něco zbrkle"},

{word: "	Set off", czWord: "	 vyrazit (na cestu)"},
{word: "	Speed up", czWord: "	 zrychlit"},
{word: "	Take off", czWord: "	 vzlétnout, odcestovat, sundat si oblečení"},
{word: "	Take out", czWord: "	 odstranit něco z kapsy nebo tašky"},
{word: "	Take up", czWord: "	 začít něco dělat"},
{word: "	Turn on", czWord: "	 zapnout"},
{word: "	Turn off", czWord: "	 vypnout"},
{word: "	Turn around", czWord: "	 otočit se, pohybovat se opačným směrem"},
{word: "	Turn up", czWord: "	 zesílit"},
{word: "	Warm up (to)", czWord: "	 začít mít někoho rád (často po předchozí nenávisti)"},
{word: "	Work out", czWord: "	 posilovat"},
{word: "	Work (something) out", czWord: "	 přijít s řešením něčeho"},
{word: "	Write down", czWord: "	 zaznamenat, zapsat si"},
{word: "	Write off", czWord: "	 odepsat"},
{word: "	Write out", czWord: "	 vypsat si"},
{word: "	Write up", czWord: "	 napsat nebo připravit si zprávu"},
{word: "	", czWord: "	"},
{word: "	My small sister broke up all plates.", czWord: "	 Moje malá sestra rozbila všechny talíře."},
{word: "	He is rentier. It brings in 3000 euro.", czWord: "	 Je rentiér. Vynáší to 3000 euro."},
{word: "	My mother brought me up without my father.", czWord: "	 Moje matka mě vychovávala be mého otce."},
{word: "	She calls on but nobody hear her voice.", czWord: "	 Volala o pomoc, ale nikdo neslyšel její hlas."},
{word: "	When we were on holyday we call on our grandmother.", czWord: "	 Když jsme byli na dovolené, tak jsme navštívili naši babičku."},
{word: "	She called off our meeting.", czWord: "	 Odvolala naše setkání."},
{word: "	Come on and cheer up! It will be better.", czWord: "	 Pojď a usměj se! Bude lépe."},
{word: "	You can come back to home, you can not go to work today.", czWord: "	 Můžeš se vrátit domů, dnes nemusíš do práce."},
{word: "	Can I come along on your trip to England?", czWord: "	 Mohu se přidat na Tvůj výlet do Anglie?"},
{word: "	I came across my old friends from school in the park.", czWord: "	 Náhodou jsem potkal staré přátele ze školy v parku."},
{word: "	I decide to cut down the shugar in the tea.", czWord: "	 Rozhodl jsem se zredukovat cukr v čaji."},
{word: "	I wanted to call you but your mother cut in me.", czWord: "	 Chtěl jsem Ti volat, ale Tvoje matka mě přerušila."},
{word: "	You must do up your seat belt in the car.", czWord: "	 Musíš si zapnout bezpečnostní pás v autě."},
{word: "	We miss three people we have to do without.", czWord: "	 Postrádáme tři lidi, musíme se obejít bez nich."},
{word: "	I dropped in Karin in her shop when I was going around.", czWord: "	 Navštívil jsem Karin v jejím obchodě, když jsem šel kolem."},
{word: "	I am hungry I will eat up everything.", czWord: "	 Jsem hladový, dojím všechno."},
{word: "	She lost balance and fell down.", czWord: "	 Ztratila rovnováhu a upadla na zem."},
{word: "	The glass was filled up I could not take it.", czWord: "	 Sklenice byla úplně plná a nemohl jsem ji vzít."},

]