export const OxfordC1:{
  word: string;
  czWord: string;
}[] = [
  {
    word: "abolish v. the tax was abolished in 197",
    czWord: "zrušit   daň byla zrušena v roce 197",
  },
  { word: "abortion n.", czWord: "potrat  " },
  { word: "absence n.", czWord: "nepřítomnos" },
  { word: "absent adj.", czWord: "nepřítomný  " },
  { word: "absurd adj.", czWord: "absurdní  " },
  { word: "abundance n.", czWord: "hojnost  " },
  {
    word: "abuse n., v. a black eye and other signs of physical abus",
    czWord: "zneužívání    monokl a další známky fyzického týrán",
  },
  { word: "academy n.", czWord: "akademie  " },
  { word: "accelerate v.", czWord: "zrychlit  " },
  { word: "acceptance n.", czWord: "přijetí  " },
  {
    word: "accessible adj. the town is accessible by bu",
    czWord: "přístupný, dostupný",
  },
  {
    word:
      "accomplishment n.  the reduction of inflation was a remarkable accomplishmen",
    czWord: "úspěch   snížení inflace bylo pozoruhodným úspěche",
  },
  {
    word: "accordance n. there is good accordance between these nation",
    czWord: "soulad  ",
  },
  {
    word:
      "accordingly adv. we have to discover what his plans are and act accordingl",
    czWord: "podle toho  musíme zjistit, jaké má plány, a podle toho jedna",
  },
  {
    word:
      "accountability n. After all, the potential for prosecution is also an important part of accountability",
    czWord:
      "odpovědnost   Potenciál k trestnímu stíhání je koneckonců také důležitou součástí odpovědnosti",
  },
  {
    word:
      "accountable adj. parents could be held accountable for their children's action",
    czWord: "odpovědnost   rodiče by mohli nést odpovědnost za činy svých dět",
  },
  {
    word: "accumulate v. her goal was to accumulate a huge fortun",
    czWord: "hromadit   jejím cílem bylo nashromáždit obrovské jměn",
  },
  {
    word: "accumulation n. the accumulation of wealt",
    czWord: "akumulace   hromadění bohatstv",
  },
  {
    word: "accusation n. there was accusation in Brian's voic",
    czWord: "obvinění   v Brianově hlase zaznělo obviněn",
  },
  {
    word:
      "accused n. the accused was ordered to stand trial on a number of charge",
    czWord:
      "obviněný   obviněnému bylo nařízeno stanout před soudem v několika bodech obžalob",
  },
  { word: "acid adj.", czWord: "kyselý  " },
  {
    word: "acquisition n. the acquisition of management skill",
    czWord: "akvizice   získání manažerských dovednost",
  },
  { word: "acre n.", czWord: "akr  " },
  { word: "activation n.", czWord: "aktivace  " },
  { word: "activist n.", czWord: "aktivista  " },
  { word: "acute adj.", czWord: "akutní  " },
  { word: "adaptation n.", czWord: "adaptace  " },
  { word: "adhere v.", czWord: "dodržovat  " },
  {
    word:
      "adjacent adj.  next to or adjoining something else. adjacent room",
    czWord: "sousední   vedle nebo vedle něčeho jiného.  sousední místnost",
  },
  {
    word: "adjustment n. I've made a few adjustments to my die",
    czWord: "úprava   Udělal jsem pár úprav ve svém jídelníčk",
  },
  { word: "administer v.", czWord: "spravovat  " },
  { word: "administrative adj.", czWord: "administrativní  " },
  { word: "administrator n.", czWord: "správce  " },
  {
    word:
      "admission n. an admission of guilt.  admission is $1 for adults and 50 cents for childre",
    czWord:
      "Přiznání, vstupné   přiznání viny. vstupné je 1 $ pro dospělé a 50 centů pro dět",
  },
  { word: "adolescent n.", czWord: "dospívající  " },
  { word: "adoption n.", czWord: "adopce  " },
  { word: "adverse adj.", czWord: "nepříznivý  " },
  { word: "advocate n., v.", czWord: "advokát  " },
  { word: "aesthetic adj.", czWord: "estetický  " },
  {
    word: "affection n. she felt affection for the wise old lad",
    czWord: "náklonnost   cítila k moudré staré paní náklonnos",
  },
  {
    word:
      "aftermath n. During this year you will suffer the aftermath of acquired wrong habits",
    czWord:
      "následky   Během tohoto roku budete trpět následky získaných nesprávných návyků",
  },
  { word: "aggression n.", czWord: "agrese  " },
  { word: "agricultural adj.", czWord: "zemědělský  " },
  {
    word:
      "aide n. an assistant to an important person, especially a political leader",
    czWord: "pobočník   asistent významné osoby, zejména politického vůdce",
  },
  {
    word: "albeit conj. he was making progress, albeit rather slowl",
    czWord: "i když   dělal pokroky, i když dost pomal",
  },
  { word: "alert v., n., adj.", czWord: "upozornění  " },
  { word: "alien adj.", czWord: "cizí  " },
  { word: "align v.", czWord: "zarovnat  " },
  { word: "alignment n.", czWord: "zarovnání  " },
  { word: "alike adv., adj.", czWord: "podobný " },
  {
    word:
      "allegation n. after leaving he made allegations of corruption against the compan",
    czWord: "obvinění   po odchodu vznesl obvinění z korupce vůči společnost",
  },
  {
    word: "allege v. he alleged that he had been assaulte",
    czWord: "tvrdit   tvrdil, že byl napade",
  },
  {
    word:
      "allegedly adv. he was allegedly a leading participant in the coup attemp",
    czWord: "údajně  byl údajně předním účastníkem pokusu o převra",
  },
  { word: "alliance n.", czWord: "aliance  " },
  {
    word: "allocate v. the authorities allocated 50,000 places to refugee",
    czWord: "přidělit   úřady přidělily uprchlíkům 50 000 mís",
  },
  {
    word: "allocation n. more efficient allocation of resource",
    czWord: "přidělení   efektivnější přidělení zdroj",
  },
  {
    word:
      "allowance n. give (someone) a sum of money regularly as an allowance",
    czWord:
      "příspěvek   dávat (někomu) pravidelně peněžní částku jako příspěvek",
  },
  { word: "ally n.", czWord: "spojenec  " },
  { word: "aluminium n.", czWord: "hliník  " },
  { word: "amateur adj., n.", czWord: "amatérský   " },
  { word: "ambassador n.", czWord: "velvyslanec  " },
  {
    word: "amend v. did she amend her original will later on",
    czWord: "upravit   pozměnila později svou původní závěť",
  },
  {
    word: "amendment n. an amendment to existing bail law",
    czWord: "pozměňovací návrh   novela stávajících zákonů o kauc",
  },
  {
    word:
      "amid prep. our dream home, set amid magnificent rolling countrysid",
    czWord:
      "uprostřed přípravy. náš vysněný dům uprostřed nádherné zvlněné krajin",
  },
  { word: "analogy n.", czWord: "analogie  " },
  { word: "anchor n.", czWord: "kotva  " },
  { word: "angel n.", czWord: "anděl  " },
  { word: "anonymous adj.", czWord: "anonymní  " },
  { word: "apparatus n.", czWord: "přístroj, zařízení  " },
  { word: "appealing adj.", czWord: "přitažlivý  " },
  { word: "appetite n.", czWord: "chuť k jídlu  " },
  { word: "applaud v.", czWord: "tleskat  " },
  { word: "applicable adj.", czWord: "použitelný  " },
  {
    word: "appoint v. she has been appointed to the boar",
    czWord: "jmenovat   byla jmenována do představenstv",
  },
  {
    word:
      "appreciation n.  the bank's lack of appreciation of their problem",
    czWord: "ocenění   banky nedoceňují jejich problém",
  },
  {
    word: "arbitrary adj. his mealtimes were entirely arbitrar",
    czWord: "libovolný   jeho doby jídla byly zcela libovoln",
  },
  { word: "architectural adj.", czWord: "architektonický  " },
  { word: "archive n.", czWord: "archiv  " },
  { word: "arena n.", czWord: "aréna  " },
  { word: "arguably adv.", czWord: "pravděpodobně " },
  { word: "arm v.", czWord: "paže  " },
  { word: "array n.", czWord: "pole  " },
  { word: "articulate v.", czWord: "artikulovat  " },
  { word: "ash n.", czWord: "popel  " },
  { word: "aspiration n.", czWord: "aspirace  " },
  { word: "aspire v.", czWord: "aspirovat  " },
  { word: "assassination n.", czWord: "atentát  " },
  { word: "assault n., v.", czWord: "útok   " },
  { word: "assemble v.", czWord: "sestavit  " },
  { word: "assembly n.", czWord: "montáž  " },
  { word: "assert v.", czWord: "tvrdit  " },
  { word: "assertion n.", czWord: "tvrzení  " },
  { word: "assurance n.", czWord: "ujištění  " },
  { word: "asylum n.", czWord: "azyl  " },
  { word: "atrocity n.", czWord: "zvěrstvo  " },
  { word: "attain v.", czWord: "dosáhnout  " },
  { word: "attendance n.", czWord: "návštěvnost  " },
  { word: "attorney n.", czWord: "advokát  " },
  { word: "attribute v., n.", czWord: "atribut   " },
  { word: "audit n.", czWord: "audit  " },
  { word: "authentic adj.", czWord: "autentický  " },
  { word: "authorize v.", czWord: "autorizovat  " },
  { word: "auto n.", czWord: "auto  " },
  { word: "autonomy n.", czWord: "autonomie  " },
  { word: "availability n.", czWord: "dostupnost  " },
  { word: "await v.", czWord: "čekat  " },
  { word: "backdrop n.", czWord: "pozadí  " },
  { word: "backing n.", czWord: "podpora  " },
  { word: "backup n.", czWord: "záloha  " },
  { word: "bail n.", czWord: "kauce  " },
  { word: "ballot n.", czWord: "hlasovací lístek  " },
  { word: "banner n.", czWord: "banner  " },
  { word: "bare adj.", czWord: "holý  " },
  { word: "barrel n.", czWord: "sud  " },
  { word: "bass1 n.", czWord: "bas1  " },
  { word: "bat v.", czWord: "netopýr  " },
  { word: "battlefield n.", czWord: "bojiště  " },
  { word: "bay n.", czWord: "zátoka  " },
  { word: "beam n.", czWord: "paprsek  " },
  { word: "beast n.", czWord: "šelma  " },
  { word: "behalf n.", czWord: "jménem  " },
  { word: "beloved adj.", czWord: "milovaný  " },
  { word: "bench n.", czWord: "lavice  " },
  { word: "benchmark n.", czWord: "benchmark  " },
  { word: "beneath prep.", czWord: "pod přípravou." },
  { word: "beneficiary n.", czWord: "příjemce  " },
  { word: "betray v.", czWord: "zradit  " },
  { word: "bind v.", czWord: "vázat  " },
  { word: "biography n.", czWord: "životopis  " },
  { word: "bishop n.", czWord: "biskup  " },
  { word: "bizarre adj.", czWord: "bizarní  " },
  { word: "blade n.", czWord: "čepel  " },
  { word: "blast n., v.", czWord: "výbuch   " },
  { word: "bleed v.", czWord: "krvácet  " },
  { word: "blend v., n.", czWord: "směs    " },
  { word: "bless v.", czWord: "požehnat  " },
  { word: "blessing n.", czWord: "požehnání  " },
  { word: "boast v.", czWord: "chlubit se  " },
  { word: "bonus n.", czWord: "bonus  " },
  { word: "boom n.", czWord: "bum  " },
  { word: "bounce v.", czWord: "odrazit  " },
  { word: "boundary n.", czWord: "hranice  " },
  { word: "bow1 v., n.", czWord: "luk1   " },
  { word: "breach n., v.", czWord: "porušení  " },
  { word: "breakdown n.", czWord: "členění  " },
  { word: "breakthrough n.", czWord: "průlom  " },
  { word: "breed v., n.", czWord: "plemeno   " },
  { word: "broadband n.", czWord: "širokopásmové připojení  " },
  { word: "browser n.", czWord: "prohlížeč  " },
  { word: "brutal adj.", czWord: "brutální  " },
  { word: "buck n.", czWord: "dolar  " },
  { word: "buddy n.", czWord: "kamarád  " },
  { word: "buffer n.", czWord: "nárazník  " },
  { word: "bulk n.", czWord: "hromadné  " },
  { word: "burden n.", czWord: "zátěž  " },
  { word: "bureaucracy n.", czWord: "byrokracie  " },
  { word: "burial n.", czWord: "pohřeb  " },
  { word: "burst v.", czWord: "prasknout  " },
  { word: "cabinet n.", czWord: "skříň  " },
  { word: "calculation n.", czWord: "výpočet  " },
  { word: "canvas n.", czWord: "plátno  " },
  { word: "capability n.", czWord: "schopnost  " },
  { word: "capitalism n.", czWord: "kapitalismus  " },
  { word: "capitalist adj.", czWord: "kapitalistický  " },
  { word: "cargo n.", czWord: "náklad  " },
  { word: "carriage n.", czWord: "kočár  " },
  { word: "carve v.", czWord: "vyřezávat  " },
  { word: "casino n.", czWord: "kasino  " },
  { word: "casualty n.", czWord: "oběť  " },
  { word: "catalogue n.", czWord: "katalog  " },
  { word: "cater v.", czWord: "obstarávat  " },
  { word: "cattle n.", czWord: "dobytek  " },
  { word: "caution n.", czWord: "pozor  " },
  { word: "cautious adj.", czWord: "opatrný  " },
  { word: "cease v.", czWord: "přestat  " },
  { word: "cemetery n.", czWord: "hřbitov  " },
  { word: "chamber n.", czWord: "komora  " },
  { word: "chaos n.", czWord: "chaos  " },
  { word: "characterize v.", czWord: "charakterizovat  " },
  { word: "charm n.", czWord: "kouzlo  " },
  { word: "charter n.", czWord: "charta  " },
  { word: "chronic adj.", czWord: "chronický  " },
  { word: "chunk n.", czWord: "kus  " },
  { word: "circulate v.", czWord: "obíhat  " },
  { word: "circulation n.", czWord: "oběh  " },
  { word: "citizenship n.", czWord: "občanství  " },
  { word: "civic adj.", czWord: "občanský  " },
  { word: "civilian n., adj.", czWord: "civilní   " },
  { word: "clarity n.", czWord: "jasnost " },
  { word: "clash n.", czWord: "střet  " },
  { word: "classification n.", czWord: "klasifikace  " },
  { word: "cling v.", czWord: "držet se  " },
  { word: "clinical adj.", czWord: "klinický  " },
  { word: "closure n.", czWord: "uzavření  " },
  { word: "cluster n.", czWord: "shluk  " },
  { word: "coalition n.", czWord: "koalice  " },
  { word: "coastal adj.", czWord: "pobřežní  " },
  { word: "cocktail n.", czWord: "koktejl  " },
  { word: "cognitive adj.", czWord: "poznávací  " },
  { word: "coincide v.", czWord: "shodují se  " },
  { word: "collaborate v.", czWord: "spolupracovat  " },
  { word: "collaboration n.", czWord: "spolupráce  " },
  { word: "collective adj.", czWord: "kolektivní  " },
  { word: "collision n.", czWord: "kolize  " },
  { word: "colonial adj.", czWord: "koloniální  " },
  { word: "columnist n.", czWord: "fejetonista  " },
  { word: "combat n., v.", czWord: "boj   " },
  { word: "commence v.", czWord: "začít  " },
  { word: "commentary n.", czWord: "komentář  " },
  { word: "commentator n.", czWord: "komentátor  " },
  { word: "commerce n.", czWord: "obchod  " },
  { word: "commissioner n.", czWord: "komisař  " },
  { word: "commodity n.", czWord: "zboží  " },
  { word: "communist adj.", czWord: "komunistický  " },
  { word: "companion n.", czWord: "společník  " },
  { word: "comparable adj.", czWord: "srovnatelný  " },
  { word: "compassion n.", czWord: "soucit  " },
  { word: "compel v.", czWord: "přinutit  " },
  { word: "compelling adj.", czWord: "přesvědčivý  " },
  { word: "compensate v.", czWord: "kompenzovat  " },
  { word: "compensation n.", czWord: "kompenzace  " },
  { word: "competence n.", czWord: "kompetence  " },
  { word: "competent adj.", czWord: "kompetentní  " },
  { word: "compile v.", czWord: "sestavit  " },
  { word: "complement v.", czWord: "doplňovat  " },
  { word: "complexity n.", czWord: "složitost  " },
  { word: "compliance n.", czWord: "soulad  " },
  { word: "complication n.", czWord: "komplikace  " },
  { word: "comply v.", czWord: "vyhovět  " },
  { word: "composition n.", czWord: "složení  " },
  { word: "compromise n., v.", czWord: "kompromis   " },
  { word: "compute v.", czWord: "vypočítat  " },
  { word: "conceal v.", czWord: "skrýt  " },
  { word: "concede v.", czWord: "připustit  " },
  { word: "conceive v.", czWord: "otěhotnět  " },
  { word: "conception n.", czWord: "početí  " },
  { word: "concession n.", czWord: "koncese  " },
  { word: "condemn v.", czWord: "odsoudit  " },
  { word: "confer v.", czWord: "udělit  " },
  { word: "confession n.", czWord: "přiznání  " },
  { word: "configuration n.", czWord: "konfigurace  " },
  { word: "confine v.", czWord: "omezit  " },
  { word: "confirmation n.", czWord: "potvrzení  " },
  { word: "confront v.", czWord: "konfrontovat  " },
  { word: "confrontation n.", czWord: "konfrontace  " },
  { word: "congratulate v.", czWord: "gratuluji  " },
  { word: "congregation n.", czWord: "sbor  " },
  { word: "congressional adj.", czWord: "kongresový  " },
  { word: "conquer v.", czWord: "dobýt  " },
  { word: "conscience n.", czWord: "svědomí  " },
  { word: "consciousness n.", czWord: "vědomí  " },
  { word: "consecutive adj.", czWord: "po sobě jdoucí  " },
  { word: "consensus n.", czWord: "konsensus  " },
  { word: "consent n., v.", czWord: "souhlas    " },
  { word: "conserve v.", czWord: "konzervovat  " },
  { word: "consistency n.", czWord: "konzistence  " },
  { word: "consolidate v.", czWord: "konsolidovat  " },
  { word: "constituency n.", czWord: "volební obvod  " },
  { word: "constitute v.", czWord: "tvoří  " },
  { word: "constitution n.", czWord: "ústava  " },
  { word: "constitutional adj.", czWord: "ústavní  " },
  { word: "constraint n.", czWord: "omezení  " },
  { word: "consultation n.", czWord: "konzultace  " },
  { word: "contemplate v.", czWord: "rozjímat  " },
  { word: "contempt n.", czWord: "pohrdání  " },
  { word: "contend v.", czWord: "zápasit  " },
  { word: "contender n.", czWord: "uchazeč  " },
  { word: "content2 adj.", czWord: "obsah2  " },
  { word: "contention n.", czWord: "spor  " },
  { word: "continually adv.", czWord: "neustále  " },
  { word: "contractor n.", czWord: "dodavatel  " },
  { word: "contradiction n.", czWord: "rozpor  " },
  { word: "contrary adj., n.", czWord: "opačný  " },
  { word: "contributor n.", czWord: "přispěvatel  " },
  { word: "conversion n.", czWord: "konverze  " },
  { word: "convict v.", czWord: "odsouzený  " },
  { word: "conviction n.", czWord: "přesvědčení  " },
  { word: "cooperate v.", czWord: "spolupracovat  " },
  { word: "cooperative adj.", czWord: "družstevní  " },
  { word: "coordinate v.", czWord: "koordinovat  " },
  { word: "coordination n.", czWord: "koordinace  " },
  { word: "coordinator n.", czWord: "koordinátor  " },
  { word: "cop n.", czWord: "policajt  " },
  { word: "copper n.", czWord: "měď  " },
  { word: "copyright n.", czWord: "autorská práva  " },
  { word: "correction n.", czWord: "oprava  " },
  { word: "correlate v.", czWord: "korelovat  " },
  { word: "correlation n.", czWord: "korelace  " },
  { word: "correspond v.", czWord: "odpovídat  " },
  { word: "correspondence n.", czWord: "korespondence  " },
  { word: "correspondent n.", czWord: "dopisovatel  " },
  { word: "corresponding adj.", czWord: "odpovídající  " },
  { word: "corrupt adj.", czWord: "zkorumpovaný  " },
  { word: "corruption n.", czWord: "korupce  " },
  { word: "costly adj.", czWord: "nákladný  " },
  { word: "councillor n.", czWord: "radní  " },
  { word: "counselling n.", czWord: "poradenství  " },
  { word: "counsellor n.", czWord: "poradce  " },
  {
    word: "counter (argue against) v.",
    czWord: "odporovat (argumentovat proti)  ",
  },
  { word: "counterpart n.", czWord: "protějšek  " },
  { word: "countless adj.", czWord: "bezpočet  " },
  { word: "coup n.", czWord: "převrat  " },
  { word: "courtesy n.", czWord: "zdvořilost  " },
  { word: "craft v.", czWord: "řemeslo  " },
  { word: "crawl v.", czWord: "plazit se  " },
  { word: "creator n.", czWord: "tvůrce  " },
  { word: "credibility n.", czWord: "důvěryhodnost  " },
  { word: "credible adj.", czWord: "věrohodný  " },
  { word: "creep v.", czWord: "plížit se  " },
  { word: "critique n.", czWord: "kritika  " },
  { word: "crown n.", czWord: "koruna  " },
  { word: "crude adj.", czWord: "hrubý  " },
  { word: "crush v.", czWord: "rozdrtit  " },
  { word: "crystal n.", czWord: "krystal  " },
  { word: "cult n., adj.", czWord: "kult   " },
  { word: "cultivate v.", czWord: "pěstovat  " },
  { word: "curiosity n.", czWord: "zvědavost  " },
  { word: "custody n.", czWord: "opatrovnictví  " },
  { word: "cutting n.", czWord: "řezání  " },
  { word: "cynical adj.", czWord: "cynický  " },
  { word: "dam n.", czWord: "sakra." },
  { word: "damaging adj.", czWord: "poškozující  " },
  { word: "dawn n.", czWord: "svítání  " },
  { word: "debris n.", czWord: "trosky  " },
  { word: "debut n.", czWord: "debut  " },
  { word: "decision-making n.", czWord: "rozhodování  " },
  { word: "decisive adj.", czWord: "rozhodný  " },
  { word: "declaration n.", czWord: "prohlášení" },
  { word: "dedicated adj.", czWord: "oddaný  " },
  { word: "dedication n.", czWord: "věnování  " },
  { word: "deed n.", czWord: "listina  " },
  { word: "deem v.", czWord: "považovat  " },
  { word: "default n.", czWord: "výchozí  " },
  { word: "defect n.", czWord: "vada  " },
  { word: "defensive adj.", czWord: "obranný  " },
  { word: "deficiency n.", czWord: "nedostatek  " },
  { word: "deficit n.", czWord: "deficit  " },
  { word: "defy v.", czWord: "vzdorovat  " },
  { word: "delegate n.", czWord: "delegát  " },
  { word: "delegation n.", czWord: "delegace  " },
  { word: "delicate adj.", czWord: "jemný  " },
  { word: "demon n.", czWord: "démon  " },
  { word: "denial n.", czWord: "popření  " },
  { word: "denounce v.", czWord: "odsuzovat  " },
  { word: "dense adj.", czWord: "hustý  " },
  { word: "density n.", czWord: "hustota  " },
  { word: "dependence n.", czWord: "závislost  " },
  { word: "depict v.", czWord: "zobrazovat  " },
  { word: "deploy v.", czWord: "nasadit  " },
  { word: "deployment n.", czWord: "nasazení  " },
  { word: "deposit v.", czWord: "vklad  " },
  { word: "deprive v.", czWord: "zbavit  " },
  { word: "deputy n.", czWord: "zástupce  " },
  { word: "descend v.", czWord: "sestoupit  " },
  { word: "descent n.", czWord: "sestup  " },
  { word: "designate v.", czWord: "jmenovat  " },
  { word: "desirable adj.", czWord: "žádoucí  " },
  { word: "desktop n.", czWord: "desktop  " },
  { word: "destructive adj.", czWord: "ničivý  " },
  { word: "detain v.", czWord: "zadržet  " },
  { word: "detection n.", czWord: "detekce  " },
  { word: "detention n.", czWord: "zadržení  " },
  { word: "deteriorate v.", czWord: "zhoršit se  " },
  { word: "devastate v.", czWord: "devastovat  " },
  { word: "devil n.", czWord: "čert  " },
  { word: "devise v.", czWord: "vymyslet  " },
  { word: "diagnose v.", czWord: "diagnostikovat  " },
  { word: "diagnosis n.", czWord: "diagnóza  " },
  { word: "dictate v.", czWord: "diktovat  " },
  { word: "dictator n.", czWord: "diktátor  " },
  { word: "differentiate v.", czWord: "odlišit  " },
  { word: "dignity n.", czWord: "důstojnost  " },
  { word: "dilemma n.", czWord: "dilema  " },
  { word: "dimension n.", czWord: "rozměr  " },
  { word: "diminish v.", czWord: "zmenšit  " },
  { word: "dip v.", czWord: "dip  " },
  { word: "diplomat n.", czWord: "diplomat  " },
  { word: "diplomatic n.", czWord: "diplomatický  " },
  { word: "directory n.", czWord: "adresář  " },
  { word: "disastrous adj.", czWord: "katastrofální  " },
  { word: "discard v.", czWord: "odhodit  " },
  { word: "discharge v.", czWord: "vypouštění  " },
  { word: "disclose v.", czWord: "zveřejnit  " },
  { word: "disclosure n.", czWord: "zveřejnění  " },
  { word: "discourse n.", czWord: "diskurz  " },
  { word: "discretion n.", czWord: "diskrétnost  " },
  { word: "discrimination n.", czWord: "diskriminace  " },
  { word: "dismissal n.", czWord: "výpověď  " },
  { word: "displace v.", czWord: "přemístit  " },
  { word: "disposal n.", czWord: "likvidace  " },
  { word: "dispose v.", czWord: "disponovat  " },
  { word: "dispute n., v.", czWord: "spor   " },
  { word: "disrupt v.", czWord: "narušit  " },
  { word: "disruption n.", czWord: "přerušení  " },
  { word: "dissolve v.", czWord: "rozpustit  " },
  { word: "distinction n.", czWord: "rozlišení  " },
  { word: "distinctive adj.", czWord: "výrazný  " },
  { word: "distort v.", czWord: "deformovat  " },
  { word: "distress n., v.", czWord: "tíseň  " },
  { word: "disturbing adj.", czWord: "rušivý  " },
  { word: "divert v.", czWord: "odklonit  " },
  { word: "divine adj.", czWord: "božský  " },
  { word: "doctrine n.", czWord: "doktrína  " },
  { word: "documentation n.", czWord: "dokumentace  " },
  { word: "domain n.", czWord: "doména  " },
  { word: "dominance n.", czWord: "dominance  " },
  { word: "donor n.", czWord: "dárce  " },
  { word: "dose n.", czWord: "dávka  " },
  { word: "drain v.", czWord: "odvod  " },
  { word: "drift v.", czWord: "drift  " },
  { word: "driving adj.", czWord: "jízdní  " },
  { word: "drown v.", czWord: "utopit se  " },
  { word: "dual adj.", czWord: "duální  " },
  { word: "dub v.", czWord: "dub  " },
  { word: "dumb adj.", czWord: "němý  " },
  { word: "duo n.", czWord: "duo  " },
  { word: "dynamic n.", czWord: "dynamický  " },
  { word: "eager adj.", czWord: "dychtivý  " },
  { word: "earnings n.", czWord: "výdělek  " },
  { word: "ease n., v.", czWord: "lehkost    " },
  { word: "echo v., n.", czWord: "echo    " },
  { word: "ecological adj.", czWord: "ekologický  " },
  { word: "educator n.", czWord: "vychovatel  " },
  { word: "effectiveness n.", czWord: "účinnost  " },
  { word: "efficiency n.", czWord: "účinnost  " },
  { word: "ego n.", czWord: "ego  " },
  { word: "elaborate adj.", czWord: "propracovaný  " },
  { word: "electoral adj.", czWord: "volební  " },
  { word: "elevate v.", czWord: "pozvednout  " },
  { word: "eligible adj.", czWord: "způsobilý  " },
  { word: "elite n.", czWord: "elita  " },
  { word: "embark v.", czWord: "nalodit se  " },
  { word: "embarrassment n.", czWord: "rozpaky  " },
  { word: "embassy n.", czWord: "velvyslanectví  " },
  { word: "embed v.", czWord: "vložit  " },
  { word: "embody v.", czWord: "ztělesňovat  " },
  { word: "emergence n.", czWord: "vznik  " },
  { word: "empirical adj.", czWord: "empirický  " },
  { word: "empower v.", czWord: "zmocnit  " },
  { word: "enact v.", czWord: "uzákonit  " },
  { word: "encompass v.", czWord: "obsáhnout  " },
  { word: "encouragement n.", czWord: "povzbuzení  " },
  { word: "encouraging adj.", czWord: "povzbuzující  " },
  { word: "endeavour n.", czWord: "snaha  " },
  { word: "endless adj.", czWord: "nekonečný  " },
  { word: "endorse v.", czWord: "podporovat  " },
  { word: "endorsement n.", czWord: "potvrzení  " },
  { word: "endure v.", czWord: "vydržet  " },
  { word: "enforce v.", czWord: "prosadit  " },
  { word: "enforcement n.", czWord: "vymáhání  " },
  { word: "engagement n.", czWord: "angažmá  " },
  { word: "engaging adj.", czWord: "poutavý  " },
  { word: "enquire v.", czWord: "zeptat se  " },
  { word: "enrich v.", czWord: "obohatit  " },
  { word: "enrol v.", czWord: "přihlásit se  " },
  { word: "ensue v.", czWord: "následovat  " },
  { word: "enterprise n.", czWord: "podnik  " },
  { word: "enthusiast n.", czWord: "nadšenec  " },
  { word: "entitle v.", czWord: "opravňovat  " },
  { word: "entity n.", czWord: "entita  " },
  { word: "epidemic n.", czWord: "epidemie  " },
  { word: "equality n.", czWord: "rovnost  " },
  { word: "equation n.", czWord: "rovnice  " },
  { word: "erect v.", czWord: "vztyčený  " },
  { word: "escalate v.", czWord: "eskalovat  " },
  { word: "essence n.", czWord: "esence  " },
  { word: "establishment n.", czWord: "provozovna  " },
  { word: "eternal adj.", czWord: "věčný  " },
  { word: "evacuate v.", czWord: "evakuovat  " },
  { word: "evoke v.", czWord: "vyvolat  " },
  { word: "evolutionary adj.", czWord: "evoluční  " },
  { word: "exaggerate v.", czWord: "přehánět  " },
  { word: "excellence n.", czWord: "excelence  " },
  { word: "exceptional adj.", czWord: "výjimečný  " },
  { word: "excess n., adj.", czWord: "nadbytek   " },
  { word: "exclusion n.", czWord: "vyloučení  " },
  { word: "exclusive adj.", czWord: "výhradní  " },
  { word: "exclusively adv.", czWord: "výhradně " },
  { word: "execute v.", czWord: "provést  " },
  { word: "execution n.", czWord: "provedení  " },
  { word: "exert v.", czWord: "vynaložit  " },
  { word: "exile n.", czWord: "vyhnanství  " },
  { word: "exit v.", czWord: "výstup  " },
  { word: "expenditure n.", czWord: "výdaj  " },
  { word: "experimental adj.", czWord: "experimentální  " },
  { word: "expire v.", czWord: "vypršet  " },
  { word: "explicit adj.", czWord: "výslovný  " },
  { word: "explicitly adv.", czWord: "výslovně " },
  { word: "exploitation n.", czWord: "vykořisťování  " },
  { word: "explosive adj., n.", czWord: "výbušný   " },
  { word: "extract v.", czWord: "extrakt  " },
  { word: "extremist n.", czWord: "extremistický  " },
  { word: "facilitate v.", czWord: "usnadnit  " },
  { word: "faction n.", czWord: "frakce  " },
  { word: "faculty n.", czWord: "fakulta  " },
  { word: "fade v.", czWord: "vyblednout  " },
  { word: "fairness n.", czWord: "spravedlnost  " },
  { word: "fatal adj.", czWord: "osudný  " },
  { word: "fate n.", czWord: "osud  " },
  { word: "favourable adj.", czWord: "příznivý  " },
  { word: "feat n.", czWord: "výkon  " },
  { word: "feminist adj., n.", czWord: "feministický   " },
  { word: "fibre n.", czWord: "vlákno  " },
  { word: "fierce adj.", czWord: "prudký  " },
  { word: "film-maker n.", czWord: "filmař  " },
  { word: "filter n., v.", czWord: "filtr    " },
  { word: "fine n., v.", czWord: "pokuta  " },
  { word: "firearm n.", czWord: "střelná zbraň  " },
  { word: "fit n.", czWord: "fit  " },
  { word: "fixture n.", czWord: "přípravek  " },
  { word: "flaw n.", czWord: "vada  " },
  { word: "flawed adj.", czWord: "vadný  " },
  { word: "flee v.", czWord: "utéct  " },
  { word: "fleet n.", czWord: "flotila  " },
  { word: "flesh n.", czWord: "maso  " },
  { word: "flexibility n.", czWord: "flexibilita  " },
  { word: "flourish v.", czWord: "vzkvétat  " },
  { word: "fluid n.", czWord: "tekutina  " },
  { word: "footage n.", czWord: "záběry  " },
  { word: "foreigner n.", czWord: "cizinec  " },
  { word: "forge v.", czWord: "kovář  " },
  { word: "formula n.", czWord: "vzorec  " },
  { word: "formulate v.", czWord: "formulovat  " },
  { word: "forth adv.", czWord: "dále ad " },
  { word: "forthcoming adj.", czWord: "nastávající  " },
  { word: "foster v.", czWord: "pěstovat  " },
  { word: "fragile adj.", czWord: "křehký  " },
  { word: "franchise n.", czWord: "franšíza  " },
  { word: "frankly adv.", czWord: "upřímně řečeno ad " },
  { word: "frustrated adj.", czWord: "frustrovaný  " },
  { word: "frustrating adj.", czWord: "frustrující  " },
  { word: "frustration n.", czWord: "frustrace  " },
  { word: "functional adj.", czWord: "funkční  " },
  { word: "fundraising n.", czWord: "fundraising  " },
  { word: "funeral n.", czWord: "pohřeb  " },
  { word: "gallon n.", czWord: "galon  " },
  { word: "gambling n.", czWord: "hazardní hry  " },
  { word: "gathering n.", czWord: "shromáždění  " },
  { word: "gaze n., v.", czWord: "pohled   " },
  { word: "gear n.", czWord: "převod  " },
  { word: "generic adj.", czWord: "druhový  " },
  { word: "genocide n.", czWord: "genocida  " },
  { word: "glance n., v.", czWord: "pohled  ,  " },
  { word: "glimpse n.", czWord: "letmý pohled  " },
  { word: "glorious adj.", czWord: "slavný  " },
  { word: "glory n.", czWord: "sláva  " },
  { word: "governance n.", czWord: "řízení  " },
  { word: "grace n.", czWord: "milost  " },
  { word: "grasp v., n.", czWord: "uchopit    " },
  { word: "grave (for dead person) n.", czWord: "hrob (pro mrtvého)  " },
  { word: "grave (serious) adj.", czWord: "hrobový (vážný)  " },
  { word: "gravity n.", czWord: "gravitace  " },
  { word: "grid n.", czWord: "mřížka  " },
  { word: "grief n.", czWord: "smutek  " },
  { word: "grin v., n.", czWord: "úsměv    " },
  { word: "grind v.", czWord: "brousit  " },
  { word: "grip n., v.", czWord: "úchop   " },
  { word: "gross adj.", czWord: "hrubý  " },
  { word: "guerrilla n.", czWord: "partyzán  " },
  { word: "guidance n.", czWord: "vedení  " },
  { word: "guilt n.", czWord: "vina  " },
  { word: "gut n.", czWord: "střevo  " },
  { word: "hail v.", czWord: "krupobití  " },
  { word: "halfway adv.", czWord: "napůl " },
  { word: "halt v., n.", czWord: "zastavit   " },
  { word: "handful n.", czWord: "hrst  " },
  { word: "handling n.", czWord: "manipulace  " },
  { word: "handy adj.", czWord: "šikovný  " },
  { word: "harassment n.", czWord: "obtěžování  " },
  { word: "hardware n.", czWord: "hardware  " },
  { word: "harmony n.", czWord: "harmonie  " },
  { word: "harsh adj.", czWord: "drsný  " },
  { word: "harvest n., v.", czWord: "sklizeň   " },
  { word: "hatred n.", czWord: "nenávist  " },
  { word: "haunt v.", czWord: "strašit  " },
  { word: "hazard n.", czWord: "nebezpečí  " },
  { word: "heighten v.", czWord: "zvýšit  " },
  { word: "heritage n.", czWord: "dědictví  " },
  { word: "hierarchy n.", czWord: "hierarchie  " },
  { word: "high-profile adj.", czWord: "vysoký profil  " },
  { word: "hint n., v.", czWord: "nápověda    " },
  { word: "homeland n.", czWord: "vlast  " },
  { word: "hook v.", czWord: "háček  " },
  { word: "hopeful adj.", czWord: "nadějný  " },
  { word: "horizon n.", czWord: "horizont  " },
  { word: "horn n.", czWord: "roh  " },
  { word: "hostage n.", czWord: "rukojmí  " },
  { word: "hostile adj.", czWord: "nepřátelský  " },
  { word: "hostility n.", czWord: "nepřátelství  " },
  { word: "humanitarian adj.", czWord: "humanitní  " },
  { word: "humanity n.", czWord: "lidskost  " },
  { word: "humble adj.", czWord: "pokorný  " },
  { word: "hydrogen n.", czWord: "vodík  " },
  { word: "identification n.", czWord: "identifikace  " },
  { word: "ideological adj.", czWord: "ideologický  " },
  { word: "ideology n.", czWord: "ideologie  " },
  { word: "idiot n.", czWord: "idiot  " },
  { word: "ignorance n.", czWord: "neznalost  " },
  { word: "imagery n.", czWord: "snímky  " },
  { word: "immense adj.", czWord: "nesmírný  " },
  { word: "imminent adj.", czWord: "hrozící  " },
  { word: "implementation n.", czWord: "realizace  " },
  { word: "imprison v.", czWord: "uvěznit  " },
  { word: "imprisonment n.", czWord: "vězení  " },
  { word: "inability n.", czWord: "neschopnost  " },
  { word: "inadequate adj.", czWord: "neadekvátní  " },
  { word: "inappropriate adj.", czWord: "nevhodný  " },
  { word: "incidence n.", czWord: "výskyt  " },
  { word: "inclined adj.", czWord: "nakloněný  " },
  { word: "inclusion n.", czWord: "zařazení  " },
  { word: "incur v.", czWord: "vyvolat  " },
  { word: "indicator n.", czWord: "indikátor  " },
  { word: "indictment n.", czWord: "obžaloba  " },
  { word: "indigenous adj.", czWord: "domorodý  " },
  { word: "induce v.", czWord: "vyvolat  " },
  { word: "indulge v.", czWord: "dopřát si  " },
  { word: "inequality n.", czWord: "nerovnost  " },
  { word: "infamous adj.", czWord: "nechvalně známý  " },
  { word: "infant n.", czWord: "kojenec  " },
  { word: "infect v.", czWord: "infikovat  " },
  { word: "inflict v.", czWord: "způsobit  " },
  { word: "influential adj.", czWord: "vlivný  " },
  { word: "inherent adj.", czWord: "inherentní  " },
  { word: "inhibit v.", czWord: "inhibovat  " },
  { word: "initiate v.", czWord: "zahájit  " },
  { word: "inject v.", czWord: "injekci  " },
  { word: "injection n.", czWord: "injekce  " },
  { word: "injustice n.", czWord: "nespravedlnost  " },
  { word: "inmate n.", czWord: "chovanec  " },
  { word: "insertion n.", czWord: "vložení  " },
  { word: "insider n.", czWord: "zasvěcenec  " },
  { word: "inspect v.", czWord: "zkontrolovat  " },
  { word: "inspection n.", czWord: "kontrola  " },
  { word: "inspiration n.", czWord: "inspirace  " },
  { word: "instinct n.", czWord: "instinkt  " },
  { word: "institutional adj.", czWord: "institucionální  " },
  { word: "instruct v.", czWord: "poučit  " },
  { word: "instrumental adj.", czWord: "instrumentální  " },
  { word: "insufficient adj.", czWord: "nedostatečný  " },
  { word: "insult n., v.", czWord: "urážka    " },
  { word: "intact adj.", czWord: "neporušený  " },
  { word: "intake n.", czWord: "příjem  " },
  { word: "integral adj.", czWord: "integrální  " },
  { word: "integrated adj.", czWord: "integrovaný  " },
  { word: "integration n.", czWord: "integrace  " },
  { word: "integrity n.", czWord: "integrita  " },
  { word: "intellectual n.", czWord: "intelektuální  " },
  { word: "intensify v.", czWord: "zesílit  " },
  { word: "intensity n.", czWord: "intenzita  " },
  { word: "intensive adj.", czWord: "intenzivní  " },
  { word: "intent n.", czWord: "záměr  " },
  { word: "interactive adj.", czWord: "interaktivní  " },
  { word: "interface n.", czWord: "rozhraní  " },
  { word: "interfere v.", czWord: "zasahovat  " },
  { word: "interference n.", czWord: "rušení  " },
  { word: "interim adj.", czWord: "prozatímní  " },
  { word: "interior adj., n.", czWord: "vnitřní    " },
  { word: "intermediate adj.", czWord: "střední  " },
  { word: "intervene v.", czWord: "zasahovat  " },
  { word: "intervention n.", czWord: "zásah  " },
  { word: "intimate adj.", czWord: "intimní  " },
  { word: "intriguing adj.", czWord: "poutavý  " },
  { word: "investigator n.", czWord: "vyšetřovatel  " },
  { word: "invisible adj.", czWord: "neviditelný  " },
  { word: "invoke v.", czWord: "vyvolat  " },
  { word: "involvement n.", czWord: "zapojení  " },
  { word: "ironic adj.", czWord: "ironický  " },
  { word: "ironically adv.", czWord: "ironicky  " },
  { word: "irony n.", czWord: "ironie  " },
  { word: "irrelevant adj.", czWord: "nepodstatný  " },
  { word: "isolation n.", czWord: "izolace  " },
  { word: "judicial adj.", czWord: "soudní  " },
  { word: "junction n.", czWord: "křižovatka  " },
  { word: "jurisdiction n.", czWord: "jurisdikce  " },
  { word: "just adj.", czWord: "jen  " },
  { word: "justification n.", czWord: "odůvodnění  " },
  { word: "kidnap v.", czWord: "unést  " },
  { word: "kidney n.", czWord: "ledvina  " },
  { word: "kingdom n.", czWord: "království  " },
  { word: "lad n.", czWord: "chlapec  " },
  { word: "landlord n.", czWord: "pronajímatel  " },
  { word: "landmark n.", czWord: "orientační bod  " },
  { word: "lap n.", czWord: "kolo  " },
  { word: "large-scale adj.", czWord: "velkoplošný  " },
  { word: "laser n.", czWord: "laser  " },
  { word: "latter adj., n.", czWord: "poslední    " },
  { word: "lawn n.", czWord: "trávník " },
  { word: "lawsuit n.", czWord: "žaloba  " },
  { word: "layout n.", czWord: "rozložení  " },
  { word: "leak v., n.", czWord: "únik   " },
  { word: "leap v., n.", czWord: "skok   " },
  { word: "legacy n.", czWord: "dědictví  " },
  { word: "legendary adj.", czWord: "legendární  " },
  { word: "legislation n.", czWord: "legislativa  " },
  { word: "legislative adj.", czWord: "legislativní  " },
  { word: "legislature n.", czWord: "zákonodárný sbor  " },
  { word: "legitimate adj.", czWord: "legitimní  " },
  { word: "lengthy adj.", czWord: "dlouhý  " },
  { word: "lesbian adj.", czWord: "lesbický  " },
  { word: "lesser adj.", czWord: "menší  " },
  { word: "lethal adj.", czWord: "smrtelný  " },
  { word: "liable adj.", czWord: "odpovědný  " },
  { word: "liberal adj., n.", czWord: "liberální    " },
  { word: "liberation n.", czWord: "osvobození  " },
  { word: "liberty n.", czWord: "svoboda  " },
  { word: "license v.", czWord: "licence  " },
  { word: "lifelong adj.", czWord: "doživotní  " },
  { word: "likelihood n.", czWord: "pravděpodobnost  " },
  { word: "limb n.", czWord: "končetina  " },
  { word: "linear adj.", czWord: "lineární  " },
  { word: "line-up n.", czWord: "sestava  " },
  { word: "linger v.", czWord: "zdržovat se  " },
  { word: "listing n.", czWord: "výpis  " },
  { word: "literacy n.", czWord: "gramotnost  " },
  { word: "liver n.", czWord: "játra  " },
  { word: "lobby n., v.", czWord: "lobby    " },
  { word: "log n., v.", czWord: "log   " },
  { word: "logic n.", czWord: "logika  " },
  { word: "long-standing adj.", czWord: "dlouholetý  " },
  { word: "long-time adj.", czWord: "dlouholetý  " },
  { word: "loom v.", czWord: "tkalcovský stav  " },
  { word: "loop n.", czWord: "smyčka  " },
  { word: "loyalty n.", czWord: "věrnost  " },
  { word: "machinery n.", czWord: "stroje  " },
  { word: "magical adj.", czWord: "kouzelný  " },
  { word: "magistrate n.", czWord: "rychtář  " },
  { word: "magnetic adj.", czWord: "magnetický  " },
  { word: "magnitude n.", czWord: "velikost  " },
  { word: "mainland n.", czWord: "pevnina  " },
  { word: "mainstream n., adj.", czWord: "hlavní proud  " },
  { word: "maintenance n.", czWord: "údržba  " },
  { word: "mandate n.", czWord: "mandát  " },
  { word: "mandatory adj.", czWord: "povinný  " },
  { word: "manifest v.", czWord: "zjevný  " },
  { word: "manipulate v.", czWord: "manipulovat  " },
  { word: "manipulation n.", czWord: "manipulace  " },
  { word: "manuscript n.", czWord: "rukopis  " },
  { word: "march n., v.", czWord: "březen  " },
  { word: "marginal adj.", czWord: "okrajový  " },
  { word: "marine adj.", czWord: "námořní  " },
  { word: "marketplace n.", czWord: "tržiště  " },
  { word: "mask n.", czWord: "maska ​​ " },
  { word: "massacre n.", czWord: "masakr  " },
  { word: "mathematical adj.", czWord: "matematický  " },
  { word: "mature adj., v.", czWord: "zralý   " },
  { word: "maximize v.", czWord: "maximalizovat  " },
  { word: "meaningful adj.", czWord: "smysluplný  " },
  { word: "meantime n.", czWord: "mezitím  " },
  { word: "medieval adj.", czWord: "středověký  " },
  { word: "meditation n.", czWord: "meditace  " },
  { word: "melody n.", czWord: "melodie  " },
  { word: "memo n.", czWord: "memorandum  " },
  { word: "memoir n.", czWord: "memoár  " },
  { word: "memorial n.", czWord: "památník  " },
  { word: "mentor n.", czWord: "mentor  " },
  { word: "merchant n.", czWord: "obchodník  " },
  { word: "mercy n.", czWord: "milosrdenství  " },
  { word: "mere adj.", czWord: "pouhý  " },
  { word: "merely adv.", czWord: "pouze ad " },
  { word: "merge v.", czWord: "sloučit  " },
  { word: "merger n.", czWord: "sloučení  " },
  { word: "merit n.", czWord: "zásluhy  " },
  { word: "methodology n.", czWord: "metodika  " },
  { word: "midst n.", czWord: "uprostřed  " },
  { word: "migration n.", czWord: "migrace  " },
  { word: "militant n., adj.", czWord: "militantní   " },
  { word: "militia n.", czWord: "milice  " },
  { word: "mill n.", czWord: "mlýn  " },
  { word: "minimal adj.", czWord: "minimální  " },
  { word: "minimize v.", czWord: "minimalizovat  " },
  { word: "mining n.", czWord: "těžba  " },
  { word: "ministry n.", czWord: "ministerstvo  " },
  { word: "minute", czWord: "minuta" },
  { word: "2 adj.", czWord: "2" },
  { word: "miracle n.", czWord: "zázrak  " },
  { word: "misery n.", czWord: "bída  " },
  { word: "misleading adj.", czWord: "zavádějící  " },
  { word: "missile n.", czWord: "střela  " },
  { word: "mob n.", czWord: "dav  " },
  { word: "mobility n.", czWord: "pohyblivost  " },
  { word: "mobilize v.", czWord: "mobilizovat  " },
  { word: "moderate adj.", czWord: "mírný  " },
  { word: "modification n.", czWord: "modifikace  " },
  { word: "momentum n.", czWord: "hybnost  " },
  { word: "monk n.", czWord: "mnich  " },
  { word: "monopoly n.", czWord: "monopol  " },
  { word: "morality n.", czWord: "morálka  " },
  { word: "motive n.", czWord: "motiv  " },
  { word: "motorist n.", czWord: "motorista  " },
  { word: "municipal adj.", czWord: "obecní  " },
  { word: "mutual adj.", czWord: "vzájemný  " },
  { word: "namely adv.", czWord: "totiž ad " },
  { word: "nationwide adj.", czWord: "celostátní  " },
  { word: "naval adj.", czWord: "námořní  " },
  { word: "neglect v., n.", czWord: "zanedbat   " },
  { word: "neighbouring adj.", czWord: "sousední  " },
  { word: "nest n.", czWord: "hnízdo  " },
  { word: "net adj.", czWord: "čistý  " },
  { word: "newsletter n.", czWord: "zpravodaj  " },
  { word: "niche n.", czWord: "výklenek  " },
  { word: "noble adj.", czWord: "vznešený  " },
  { word: "nod v.", czWord: "kývnout  " },
  { word: "nominate v.", czWord: "nominovat  " },
  { word: "nomination n.", czWord: "nominace  " },
  { word: "nominee n.", czWord: "kandidát  " },
  { word: "nonetheless adv.", czWord: "nicméně " },
  { word: "non-profit adj.", czWord: "neziskový  " },
  { word: "nonsense n.", czWord: "nesmysl  " },
  { word: "noon n.", czWord: "poledne  " },
  { word: "notable adj.", czWord: "pozoruhodný  " },
  { word: "notably adv.", czWord: "zejména " },
  { word: "notify v.", czWord: "oznámit  " },
  { word: "notorious adj.", czWord: "notoricky známý  " },
  { word: "novel adj.", czWord: "románový  " },
  { word: "nursery n.", czWord: "školka  " },
  { word: "objection n.", czWord: "námitka  " },
  { word: "oblige v.", czWord: "zavázat  " },
  { word: "obsess v.", czWord: "posedlý  " },
  { word: "obsession n.", czWord: "posedlost  " },
  { word: "occasional adj.", czWord: "občasný  " },
  { word: "occurrence n.", czWord: "výskyt" },
  { word: "odds n. 	", czWord: "kurz" },
  { word: "offering n. 	", czWord: "nabídka" },
  { word: "offspring n. 	", czWord: "potomek" },
  { word: "operational adj. 	", czWord: "provozní" },
  { word: "opt v. 	", czWord: "opt" },
  { word: "optical adj. 	", czWord: "optický" },
  { word: "optimism n. 	", czWord: "optimismus" },
  { word: "oral adj. 	", czWord: "ústní" },
  { word: "organizational adj. 	", czWord: "organizační" },
  { word: "orientation n. 	", czWord: "orientace" },
  { word: "originate v. 	", czWord: "původ" },
  { word: "outbreak n. 	", czWord: "ohnisko" },
  { word: "outing n. 	", czWord: "výlet" },
  { word: "outlet n. 	", czWord: "vývod" },
  { word: "outlook n. 	", czWord: "výhled" },
  { word: "outrage n., v. 	", czWord: "pobouření  	" },
  { word: "outsider n. 	", czWord: "outsider" },
  { word: "overlook v. 	", czWord: "přehlédnout" },
  { word: "overly adv. 	", czWord: "přehnaně  	" },
  { word: "oversee v. 	", czWord: "dohlížet" },
  { word: "overturn v. 	", czWord: "převrátit" },
  { word: "overwhelm v. 	", czWord: "přemoci" },
  { word: "overwhelming adj. 	", czWord: "ohromující" },
  { word: "pad n. 	", czWord: "podložka" },
  { word: "parameter n. 	", czWord: "parametr" },
  { word: "parental adj. 	", czWord: "rodičovský" },
  { word: "parish n. 	", czWord: "farnost" },
  { word: "parliamentary adj. 	", czWord: "parlamentní" },
  { word: "partial adj. 	", czWord: "částečný" },
  { word: "partially adv. 	", czWord: "částečně  	" },
  { word: "passing n. 	", czWord: "míjení" },
  { word: "passive adj. 	", czWord: "pasivní" },
  { word: "pastor n. 	", czWord: "farář" },
  { word: "patch n. 	", czWord: "náplast" },
  { word: "patent n. 	", czWord: "patent" },
  { word: "pathway n. 	", czWord: "cesta" },
  { word: "patrol n., v. 	", czWord: "hlídka" },
  { word: "patron n. 	", czWord: "patron" },
  { word: "peak n. 	", czWord: "vrchol" },
  { word: "peasant n. 	", czWord: "rolník" },
  { word: "peculiar adj. 	", czWord: "zvláštní" },
  { word: "persist v. 	", czWord: "trvat" },
  { word: "persistent adj. 	", czWord: "vytrvalý" },
  { word: "personnel n. 	", czWord: "personál" },
  { word: "petition n. 	", czWord: "petice" },
  { word: "philosopher n. 	", czWord: "filozof" },
  { word: "philosophical adj. 	", czWord: "filozofický" },
  { word: "physician n. 	", czWord: "lékař" },
  { word: "pioneer n., v. 	", czWord: "průkopník " },
  { word: "pipeline n. 	", czWord: "potrubí" },
  { word: "pirate n. 	", czWord: "pirát" },
  { word: "pit n. 	", czWord: "jáma" },
  { word: "plea n. 	", czWord: "prosba" },
  { word: "plead v. 	", czWord: "prosit" },
  { word: "pledge v., n. 	", czWord: "zástava  " },
  { word: "plug v., n. 	", czWord: "zástrčka  " },
  { word: "plunge v. 	", czWord: "ponořit se" },
  { word: "pole n. 	", czWord: "pól" },
  { word: "poll n. 	", czWord: "anketa" },
  { word: "pond n. 	", czWord: "rybník" },
  { word: "pop v. 	", czWord: "pop" },
  { word: "portfolio n. 	", czWord: "portfolio" },
  { word: "portray v. 	", czWord: "vylíčit" },
  { word: "postpone v. 	", czWord: "odložit" },
  { word: "post-war adj. 	", czWord: "poválečný" },
  { word: "practitioner n. 	", czWord: "praktik" },
  { word: "preach v. 	", czWord: "kázat" },
  { word: "precedent n. 	", czWord: "precedens" },
  { word: "precision n. 	", czWord: "přesnost" },
  { word: "predator n. 	", czWord: "dravec" },
  { word: "predecessor n. 	", czWord: "předchůdce" },
  { word: "predominantly adv. 	", czWord: "převážně  	" },
  { word: "pregnancy n. 	", czWord: "těhotenství" },
  { word: "prejudice n. 	", czWord: "předsudek" },
  { word: "preliminary adj. 	", czWord: "předběžný" },
  { word: "premier n. 	", czWord: "premiér" },
  { word: "premise n. 	", czWord: "předpoklad" },
  { word: "premium n. 	", czWord: "prémie" },
  { word: "prescribe v. 	", czWord: "předepsat" },
  { word: "prescription n. 	", czWord: "předpis" },
  { word: "presently adv. 	", czWord: "v současnosti" },
  { word: "preservation n. 	", czWord: "konzervace" },
  { word: "preside v. 	", czWord: "předsedat" },
  { word: "presidency n. 	", czWord: "předsednictvo" },
  { word: "presidential adj. 	", czWord: "prezidentský" },
  { word: "prestigious adj. 	", czWord: "prestižní" },
  { word: "presumably adv. 	", czWord: "pravděpodobně" },
  { word: "presume v. 	", czWord: "předpokládat" },
  { word: "prevail v. 	", czWord: "převládnout" },
  { word: "prevalence n. 	", czWord: "prevalence" },
  { word: "prevention n. 	", czWord: "prevence" },
  { word: "prey n. 	", czWord: "kořist" },
  { word: "principal n. 	", czWord: "hlavní" },
  { word: "privatization n. 	", czWord: "privatizace" },
  { word: "privilege n. 	", czWord: "privilegium" },
  { word: "probe n., v. 	", czWord: "sonda  " },
  { word: "problematic adj. 	", czWord: "problematický" },
  { word: "proceedings n. 	", czWord: "řízení" },
  { word: "proceeds n. 	", czWord: "výtěžek" },
  { word: "processing n. 	", czWord: "zpracování" },
  { word: "processor n. 	", czWord: "procesor" },
  { word: "proclaim v. 	", czWord: "prohlásit" },
  { word: "productive adj. 	", czWord: "produktivní" },
  { word: "productivity n. 	", czWord: "produktivita" },
  { word: "profitable adj. 	", czWord: "výnosný" },
  { word: "profound adj. 	", czWord: "hluboký" },
  { word: "projection n. 	", czWord: "projekce" },
  { word: "prominent adj. 	", czWord: "prominentní" },
  { word: "pronounced adj. 	", czWord: "vyslovený" },
  { word: "propaganda n. 	", czWord: "propaganda" },
  { word: "proposition n. 	", czWord: "návrh" },
  { word: "prosecute v. 	", czWord: "stíhat" },
  { word: "prosecution n. 	", czWord: "stíhání" },
  { word: "prosecutor n. 	", czWord: "státní zástupce" },
  { word: "prospective adj. 	", czWord: "výhledový" },
  { word: "prosperity n. 	", czWord: "prosperita" },
  { word: "protective adj. 	", czWord: "ochranný" },
  { word: "protocol n. 	", czWord: "protokol" },
  { word: "province n. 	", czWord: "provincie" },
  { word: "provincial adj. 	", czWord: "zemský" },
  { word: "provision n. 	", czWord: "ustanovení" },
  { word: "provoke v. 	", czWord: "provokovat" },
  { word: "psychiatric adj. 	", czWord: "psychiatrický" },
  { word: "pulse n. 	", czWord: "puls" },
  { word: "pump v., n. 	", czWord: "čerpadlo " },
  { word: "punch n., v. 	", czWord: "úder" },
  { word: "query n. 	", czWord: "dotaz" },
  { word: "quest n. 	", czWord: "pátrání" },
  { word: "quota n. 	", czWord: "kvóta" },
  { word: "radar n. 	", czWord: "radar" },
  { word: "radical adj. 	", czWord: "radikální" },
  { word: "rage n. 	", czWord: "vztek" },
  { word: "raid n., v. 	", czWord: "nájezd  " },
  { word: "rally n., v. 	", czWord: "rally  " },
  { word: "ranking n. 	", czWord: "pořadí" },
  { word: "rape n., v. 	", czWord: "znásilnění " },
  { word: "ratio n. 	", czWord: "poměr" },
  { word: "rational adj. 	", czWord: "rozumný" },
  { word: "ray n. 	", czWord: "paprsek" },
  { word: "readily adv. 	", czWord: "snadno  	" },
  { word: "realization n. 	", czWord: "realizace" },
  { word: "realm n. 	", czWord: "říše" },
  { word: "rear adj., n. 	", czWord: "zadní  " },
  { word: "reasoning n. 	", czWord: "úvaha" },
  { word: "reassure v. 	", czWord: "uklidnit" },
  { word: "rebel n. 	", czWord: "rebel" },
  { word: "rebellion n. 	", czWord: "povstání" },
  { word: "recipient n. 	", czWord: "příjemce" },
  { word: "reconstruction n. 	", czWord: "rekonstrukce" },
  { word: "recount1 v. 	", czWord: "vyprávění" },
  { word: "referendum n. 	", czWord: "referendum" },
  { word: "reflection n. 	", czWord: "odraz" },
  { word: "reform n., v. 	", czWord: "reforma  " },
  { word: "refuge n. 	", czWord: "útočiště" },
  { word: "refusal n. 	", czWord: "odmítnutí" },
  { word: "regain v. 	", czWord: "získat zpět" },
  { word: "regardless adv. 	", czWord: "bez ohledu na  	" },
  { word: "regime n. 	", czWord: "režim" },
  { word: "regulator n. 	", czWord: "regulátor" },
  { word: "regulatory adj. 	", czWord: "regulační" },
  { word: "rehabilitation n. 	", czWord: "rehabilitace" },
  { word: "reign n., v. 	", czWord: "panovat " },
  { word: "rejection n. 	", czWord: "odmítnutí  	" },
  { word: "relevance n. 	", czWord: "relevance" },
  { word: "reliability n. 	", czWord: "spolehlivost" },
  { word: "reluctant adj. 	", czWord: "zdráhavý" },
  { word: "remainder n. 	", czWord: "zbytek" },
  { word: "remains n. 	", czWord: "zůstává" },
  { word: "remedy n. 	", czWord: "náprava" },
  { word: "reminder n. 	", czWord: "upomínka" },
  { word: "removal n. 	", czWord: "odstranění" },
  { word: "render v. 	", czWord: "render" },
  { word: "renew v. 	", czWord: "obnovit" },
  { word: "renowned adj. 	", czWord: "proslulý" },
  { word: "rental n. 	", czWord: "pronájem" },
  { word: "replacement n. 	", czWord: "výměna" },
  { word: "reportedly adv. 	", czWord: "údajně  	" },
  { word: "representation n. 	", czWord: "reprezentace" },
  { word: "reproduce v. 	", czWord: "reprodukovat" },
  { word: "reproduction n. 	", czWord: "reprodukce" },
  { word: "republic n. 	", czWord: "republika" },
  { word: "resemble v. 	", czWord: "podobat se" },
  { word: "reside v. 	", czWord: "bydlet" },
  { word: "residence n. 	", czWord: "bydliště" },
  { word: "residential adj. 	", czWord: "obytný" },
  { word: "residue n. 	", czWord: "zbytek" },
  { word: "resignation n. 	", czWord: "rezignace" },
  { word: "resistance n. 	", czWord: "odpor" },
  { word: "respective adj. 	", czWord: "příslušný" },
  { word: "respectively adv. 	", czWord: "respektive ad  	" },
  { word: "restoration n. 	", czWord: "restaurování" },
  { word: "restraint n. 	", czWord: "omezení" },
  { word: "resume v. 	", czWord: "životopis" },
  { word: "retreat n., v. 	", czWord: "ústup  " },
  { word: "retrieve v. 	", czWord: "získat" },
  { word: "revelation n. 	", czWord: "zjevení" },
  { word: "revenge n. 	", czWord: "pomsta" },
  { word: "reverse v. , n., adj. 	", czWord: "obrace  " },
  { word: "revival n. 	", czWord: "oživení" },
  { word: "revive v. 	", czWord: "oživit" },
  { word: "revolutionary adj. 	", czWord: "revoluční" },
  { word: "rhetoric n. 	", czWord: "rétorika" },
  { word: "rifle n. 	", czWord: "puška" },
  { word: "riot n. 	", czWord: "vzpoura" },
  { word: "rip v. 	", czWord: "roztrhnout" },
  { word: "ritual n. 	", czWord: "rituál" },
  { word: "robust adj. 	", czWord: "robustní" },
  { word: "rock v. 	", czWord: "rock" },
  { word: "rod n. 	", czWord: "tyč" },
  { word: "rotate v. 	", czWord: "otočit" },
  { word: "rotation n. 	", czWord: "rotace" },
  { word: "ruling n. 	", czWord: "vládnoucí" },
  { word: "rumour n. 	", czWord: "pověst" },
  { word: "sack v. 	", czWord: "pytel" },
  { word: "sacred adj. 	", czWord: "posvátný" },
  { word: "sacrifice n., v. 	", czWord: "obětovat" },
  { word: "saint n. 	", czWord: "svatý" },
  { word: "sake n. 	", czWord: "sake" },
  { word: "sanction n. 	", czWord: "sankce" },
  { word: "say n. 	", czWord: "řekni" },
  { word: "scattered adj. 	", czWord: "rozptýlený" },
  { word: "sceptical adj. 	", czWord: "skeptický" },
  { word: "scope n. 	", czWord: "rozsah" },
  { word: "screw v., n. 	", czWord: "šroub " },
  { word: "scrutiny n. 	", czWord: "kontrola" },
  { word: "seal v., n. 	", czWord: "pečeť " },
  { word: "secular adj. 	", czWord: "světský" },
  { word: "seemingly adv. 	", czWord: "zdánlivě" },
  { word: "segment n. 	", czWord: "segment" },
  { word: "seize v. 	", czWord: "chytit" },
  { word: "seldom adv. 	", czWord: "zřídka  	" },
  { word: "selective adj. 	", czWord: "selektivní" },
  { word: "senator n. 	", czWord: "senátor" },
  { word: "sensation n. 	", czWord: "pocit" },
  { word: "sensitivity n. 	", czWord: "citlivost" },
  { word: "sentiment n. 	", czWord: "sentiment" },
  { word: "separation n. 	", czWord: "oddělení" },
  { word: "serial adj. 	", czWord: "řadový" },
  { word: "settlement n. 	", czWord: "osada" },
  { word: "set-up n. 	", czWord: "nastavení" },
  { word: "sexuality n. 	", czWord: "sexualita" },
  { word: "shareholder n. 	", czWord: "akcionář" },
  { word: "shatter v. 	", czWord: "rozbít" },
  { word: "shed v. 	", czWord: "bouda" },
  { word: "sheer adj. 	", czWord: "čirý" },
  { word: "shipping n. 	", czWord: "doprava" },
  { word: "shoot n. 	", czWord: "střílet" },
  { word: "shrink v. 	", czWord: "zmenšit" },
  { word: "shrug v. 	", czWord: "pokrčit rameny" },
  { word: "sigh v., n. 	", czWord: "povzdech  " },
  { word: "simulate v. 	", czWord: "simulovat" },
  { word: "simulation n. 	", czWord: "simulace" },
  { word: "simultaneously adv. 	", czWord: "současně" },
  { word: "sin n. 	", czWord: "hřích" },
  { word: "situated adj. 	", czWord: "umístěný" },
  { word: "sketch n. 	", czWord: "skica" },
  { word: "skip v. 	", czWord: "přeskočit" },
  { word: "slam v. 	", czWord: "bouchnout" },
  { word: "slap v. 	", czWord: "facka" },
  { word: "slash v. 	", czWord: "lomítko" },
  { word: "slavery n. 	", czWord: "otroctví" },
  { word: "slot n. 	", czWord: "slot" },
  { word: "smash v. 	", czWord: "rozbít" },
  { word: "snap v. 	", czWord: "snap" },
  { word: "soak v. 	", czWord: "namočit" },
  { word: "soar v. 	", czWord: "stoupat" },
  { word: "socialist adj. 	", czWord: "socialistický" },
  { word: "sole adj. 	", czWord: "jediný" },
  { word: "solely adv. 	", czWord: "pouze  	" },
  { word: "solicitor n. 	", czWord: "advokát" },
  { word: "solidarity n. 	", czWord: "solidarita" },
  { word: "solo adj., n. 	", czWord: "sólo  " },
  { word: "sound adj. 	", czWord: "zvuk" },
  { word: "sovereignty n. 	", czWord: "suverenita" },
  { word: "spam n. 	", czWord: "spam" },
  { word: "span v., n. 	", czWord: "rozpětí " },
  { word: "spare v. 	", czWord: "náhradní" },
  { word: "spark v. 	", czWord: "jiskra" },
  { word: "specialized adj. 	", czWord: "specializovaný" },
  { word: "specification n. 	", czWord: "specifikace" },
  { word: "specimen n. 	", czWord: "exemplář" },
  { word: "spectacle n. 	", czWord: "podívaná" },
  { word: "spectrum n. 	", czWord: "spektrum" },
  { word: "spell n. 	", czWord: "kouzlo" },
  { word: "sphere n. 	", czWord: "koule" },
  { word: "spin v., n. 	", czWord: "spin " },
  { word: "spine n. 	", czWord: "páteř" },
  { word: "spotlight n. 	", czWord: "reflektor" },
  { word: "spouse n. 	", czWord: "manžel" },
  { word: "spy n., v. 	", czWord: "špion " },
  { word: "squad n. 	", czWord: "četa" },
  { word: "squeeze v. 	", czWord: "zmáčknout" },
  { word: "stab v. 	", czWord: "bodnout" },
  { word: "stability n. 	", czWord: "stabilita" },
  { word: "stabilize v. 	", czWord: "stabilizovat" },
  { word: "stake n. 	", czWord: "kůl" },
  { word: "standing adj. 	", czWord: "stojící" },
  { word: "stark adj. 	", czWord: "ostrý" },
  { word: "statistical adj. 	", czWord: "statistický" },
  { word: "steer v. 	", czWord: "řídit" },
  { word: "stem n., v. 	", czWord: "kmen " },
  { word: "stereotype n. 	", czWord: "stereotyp" },
  { word: "stimulus n. 	", czWord: "podnět" },
  { word: "stir v. 	", czWord: "míchat" },
  { word: "storage n. 	", czWord: "sklad" },
  { word: "straightforward adj. 	", czWord: "přímočarý" },
  { word: "strain n. 	", czWord: "kmen" },
  { word: "strand n. 	", czWord: "pramen" },
  { word: "strategic adj. 	", czWord: "strategický" },
  { word: "striking adj. 	", czWord: "úderný" },
  {
    word: "strip (long narrow piece) n. 	",
    czWord: "proužek (dlouhý úzký kus)",
  },
  {
    word: "strip (remove clothes/a layer) v. 	",
    czWord: "svléknout (sejmout oblečení/vrstvu)",
  },
  { word: "strive v. 	", czWord: "snažit se" },
  { word: "structural adj. 	", czWord: "strukturální" },
  { word: "stumble v. 	", czWord: "klopýtnout" },
  { word: "stun v. 	", czWord: "omráčit" },
  { word: "submission n. 	", czWord: "podání" },
  { word: "subscriber n. 	", czWord: "předplatitel" },
  { word: "subscription n. 	", czWord: "předplatné" },
  { word: "subsidy n. 	", czWord: "dotace" },
  { word: "substantial adj. 	", czWord: "podstatný" },
  { word: "substantially adv. 	", czWord: "podstatně ad  	" },
  { word: "substitute n., v. 	", czWord: "náhradní  " },
  { word: "substitution n. 	", czWord: "substituce" },
  { word: "subtle adj. 	", czWord: "jemný" },
  { word: "suburban adj. 	", czWord: "předměstský" },
  { word: "succession n. 	", czWord: "posloupnost" },
  { word: "successive adj. 	", czWord: "postupný" },
  { word: "successor n. 	", czWord: "nástupce" },
  { word: "suck v. 	", czWord: "sát" },
  { word: "sue v. 	", czWord: "žalovat" },
  { word: "suicide n. 	", czWord: "sebevražda" },
  { word: "suite n. 	", czWord: "apartmá" },
  { word: "summit n. 	", czWord: "vrchol" },
  { word: "superb adj. 	", czWord: "skvělý" },
  { word: "superior adj. 	", czWord: "nadřazený" },
  { word: "supervise v. 	", czWord: "dohlížet" },
  { word: "supervision n. 	", czWord: "dozor" },
  { word: "supervisor n. 	", czWord: "vedoucí" },
  { word: "supplement n., v. 	", czWord: "doplněk  " },
  { word: "supportive adj. 	", czWord: "podpůrný" },
  { word: "supposedly adv. 	", czWord: "prý ad  	" },
  { word: "suppress v. 	", czWord: "potlačit" },
  { word: "supreme adj. 	", czWord: "nejvyšší" },
  { word: "surge n., v. 	", czWord: "přepětí " },
  { word: "surgical adj. 	", czWord: "chirurgický" },
  { word: "surplus n. 	", czWord: "přebytek" },
  { word: "surrender v. 	", czWord: "vzdát se" },
  { word: "surveillance n. 	", czWord: "dohled" },
  { word: "suspension n. 	", czWord: "zavěšení" },
  { word: "suspicion n. 	", czWord: "podezření" },
  { word: "suspicious adj. 	", czWord: "podezřelý" },
  { word: "sustain v. 	", czWord: "udržet" },
  { word: "swing v., n. 	", czWord: "houpačka  " },
  { word: "sword n. 	", czWord: "meč" },
  { word: "symbolic adj. 	", czWord: "symbolický" },
  { word: "syndrome n. 	", czWord: "syndrom" },
  { word: "synthesis n. 	", czWord: "syntéza" },
  { word: "systematic adj. 	", czWord: "systematický" },
  { word: "tackle n. 	", czWord: "řešit" },
  { word: "tactic n. 	", czWord: "taktika" },
  { word: "tactical adj. 	", czWord: "taktický" },
  { word: "taxpayer n. 	", czWord: "daňový poplatník" },
  { word: "tempt v. 	", czWord: "pokoušet" },
  { word: "tenant n. 	", czWord: "nájemník" },
  { word: "tender adj. 	", czWord: "něžný" },
  { word: "tenure n. 	", czWord: "funkční období" },
  { word: "terminal adj. 	", czWord: "koncový" },
  { word: "terminate v. 	", czWord: "ukončit" },
  { word: "terrain n. 	", czWord: "terén" },
  { word: "terrific adj. 	", czWord: "skvělý" },
  { word: "testify v. 	", czWord: "svědčit" },
  { word: "testimony n. 	", czWord: "svědectví" },
  { word: "texture n. 	", czWord: "textura" },
  { word: "thankfully adv. 	", czWord: "naštěstí" },
  { word: "theatrical adj. 	", czWord: "divadelní" },
  { word: "theology n. 	", czWord: "teologie" },
  { word: "theoretical adj. 	", czWord: "teoretický" },
  { word: "thereafter adv. 	", czWord: "poté ad  	" },
  { word: "thereby adv. 	", czWord: "tím ad  	" },
  { word: "thoughtful adj. 	", czWord: "přemýšlivý" },
  { word: "thought-provoking adj. 	", czWord: "myšlenkový" },
  { word: "thread n. 	", czWord: "závit" },
  { word: "threshold n. 	", czWord: "práh" },
  { word: "thrilled adj. 	", czWord: "nadšený" },
  { word: "thrive v. 	", czWord: "prospívat" },
  { word: "tide n. 	", czWord: "příliv" },
  { word: "tighten v. 	", czWord: "utáhnout" },
  { word: "timber n. 	", czWord: "dřevo" },
  { word: "timely adj. 	", czWord: "včasný" },
  { word: "tobacco n. 	", czWord: "tabák" },
  { word: "tolerance n. 	", czWord: "tolerance" },
  { word: "tolerate v. 	", czWord: "tolerovat" },
  { word: "toll n. 	", czWord: "mýtné" },
  { word: " 	", czWord: " 	" },
  { word: "top v. 	", czWord: "horní" },
  { word: "torture n., v. 	", czWord: "mučení  " },
  { word: "toss v. 	", czWord: "hodit" },
  { word: "total v. 	", czWord: "celkem" },
  { word: "toxic adj. 	", czWord: "jedovatý" },
  { word: "trace n. 	", czWord: "stopa" },
  { word: "trademark n. 	", czWord: "ochranná známka" },
  { word: "trail n., v. 	", czWord: "stezka " },
  { word: "trailer n. 	", czWord: "přívěs" },
  { word: "transaction n. 	", czWord: "transakce" },
  { word: "transcript n. 	", czWord: "přepis" },
  { word: "transformation n. 	", czWord: "transformace" },
  { word: "transit n. 	", czWord: "tranzit" },
  { word: "transmission n. 	", czWord: "přenos" },
  { word: "transparency n. 	", czWord: "průhlednost" },
  { word: "transparent adj. 	", czWord: "průhledný" },
  { word: "trauma n. 	", czWord: "trauma" },
  { word: "treaty n. 	", czWord: "smlouva" },
  { word: "tremendous adj. 	", czWord: "ohromný" },
  { word: "tribal adj. 	", czWord: "kmenový" },
  { word: "tribunal n. 	", czWord: "tribunál" },
  { word: "tribute n. 	", czWord: "hold" },
  { word: "trigger n. 	", czWord: "spoušť" },
  { word: "trio n. 	", czWord: "trio" },
  { word: "triumph n. 	", czWord: "triumf" },
  { word: "trophy n. 	", czWord: "trofej" },
  { word: "troubled adj. 	", czWord: "utrápený" },
  { word: "trustee n. 	", czWord: "správce" },
  { word: "tuition n. 	", czWord: "školné" },
  { word: "turnout n. 	", czWord: "výhybka" },
  { word: "turnover n. 	", czWord: "obrat" },
  { word: "twist v., n. 	", czWord: "kroutit " },
  { word: "undergraduate n. 	", czWord: "vysokoškolák" },
  { word: "underlying adj. 	", czWord: "podkladový" },
  { word: "undermine v. 	", czWord: "podkopat" },
  { word: "undoubtedly adv. 	", czWord: "nepochybně ad  	" },
  { word: "unify v. 	", czWord: "sjednotit" },
  { word: "unprecedented adj. 	", czWord: "nebývalý" },
  { word: "unveil v. 	", czWord: "odhalit" },
  { word: "upcoming adj. 	", czWord: "nadcházející" },
  { word: "upgrade v., n. 	", czWord: "upgrade " },
  { word: "uphold v. 	", czWord: "podporovat" },
  { word: "utility n. 	", czWord: "užitná" },
  { word: "utilize v. 	", czWord: "využít" },
  { word: "utterly adv. 	", czWord: "zcela ad  	" },
  { word: "vacuum n. 	", czWord: "vakuum" },
  { word: "vague adj. 	", czWord: "neurčitý" },
  { word: "validity n. 	", czWord: "platnost" },
  { word: "vanish v. 	", czWord: "zmizet" },
  { word: "variable n., adj. 	", czWord: "proměnný" },
  { word: "varied adj. 	", czWord: "rozmanitý" },
  { word: "vein n. 	", czWord: "žíla" },
  { word: "venture n., v. 	", czWord: "podnik" },
  { word: "verbal adj. 	", czWord: "slovesný" },
  { word: "verdict n. 	", czWord: "verdikt" },
  { word: "verify v. 	", czWord: "ověřit" },
  { word: "verse n. 	", czWord: "verš" },
  { word: "versus prep. 	", czWord: "oproti  	" },
  { word: "vessel n. 	", czWord: "nádoba" },
  { word: "veteran n. 	", czWord: "veterán" },
  { word: "viable adj. 	", czWord: "životaschopný" },
  { word: "vibrant adj. 	", czWord: "vibrující" },
  { word: "vice n. 	", czWord: "vice" },
  { word: "vicious adj. 	", czWord: "zlomyslný" },
  { word: "villager n. 	", czWord: "vesničan" },
  { word: "violate v. 	", czWord: "porušovat" },
  { word: "violation n. 	", czWord: "porušení" },
  { word: "virtue n. 	", czWord: "ctnost" },
  { word: "vocal adj. 	", czWord: "vokální" },
  { word: "vow v. 	", czWord: "slib" },
  { word: "vulnerability n. 	", czWord: "zranitelnost" },
  { word: "vulnerable adj. 	", czWord: "zranitelný" },
  { word: "ward n. 	", czWord: "oddělení" },
  { word: "warehouse n. 	", czWord: "sklad" },
  { word: "warfare n. 	", czWord: "válčení" },
  { word: "warrant n., v. 	", czWord: "příkaz" },
  { word: "warrior n. 	", czWord: "válečník" },
  { word: "weaken v. 	", czWord: "oslabit" },
  { word: "weave v. 	", czWord: "tkát" },
  { word: "weed n. 	", czWord: "plevel" },
  { word: "well n. 	", czWord: "dobře" },
  { word: "well-being n. 	", czWord: "pohoda" },
  { word: "whatsoever adv. 	", czWord: "cokoliv  	" },
  { word: "whereby adv. 	", czWord: "čímž  	" },
  { word: "whilst conj. 	", czWord: "zatímco" },
  { word: "whip v. 	", czWord: "bič" },
  { word: "wholly adv. 	", czWord: "zcela" },
  { word: "widen v. 	", czWord: "rozšířit" },
  { word: "widow n. 	", czWord: "vdova" },
  { word: "width n. 	", czWord: "šířka" },
  { word: "willingness n. 	", czWord: "ochota" },
  { word: "wipe v. 	", czWord: "vymazat" },
  { word: "wit n. 	", czWord: "vtip" },
  { word: "withdrawal n. 	", czWord: "stažení" },
  { word: "workout n. 	", czWord: "cvičení" },
  { word: "worship n., v. 	", czWord: "uctívání  " },
  { word: "worthwhile adj. 	", czWord: "hodný" },
  { word: "worthy adj. 	", czWord: "hodný" },
  { word: "yell v. 	", czWord: "křičet" },
  { word: "yield n., v. 	", czWord: "výnos  " },
  { word: "youngster n 	", czWord: "mladík  	" },
];
