export const OxfordB1: {
czWord: string;
word: string;
sentenceExample?: string;
}[] = [
  {
    czWord: "minus pět stupňů",
    word: "minus five degrees, five degrees below zero",
  },
  { czWord: "velká písmena", word: "capital letters" },
  { czWord: "trest smrti", word: "capital punishment, death penalty" },
  { czWord: "graf, schéma", word: "chart" },
  { czWord: "Jak daleko je to odtud?", word: "How far is it from here?" },
  {
    czWord: "Válka skončila, spory však pokračují.",
    word: "The war is over, however the disputes go on",
  },
  { czWord: "široko daleko", word: "near and far" },
  { czWord: "na protější straně", word: "on the opposite side" },
  { czWord: "zkušební lhůta", word: "probationary period" },
  { czWord: "záruční lhůta/doba", word: "warranty period" },
  { czWord: "zkušební doba před přijetím do práce", word: "probation (period)" },
  { czWord: "přesně jedna libra", word: "an even pound" },
  { czWord: "v praxi, ve skutečnosti, fakticky", word: "in practice" },
  { czWord: "být ze cviku", word: "be out of practice" },
  { czWord: "provádět rituály", word: "practise rituals" },
  { czWord: "Voda je pěkně studená.", word: "The water is pretty cold" },
  { czWord: "celkem jednoduše", word: "quite simply" },
  { czWord: "Celkem se mi to líbilo.", word: "I quite liked it." },
  { czWord: "příšerný nepořádek", word: "terrible mess" },
  { czWord: "Hrozně jsi mě vylekal.", word: "You gave me a terrible fright." },
  { czWord: "strašná nehoda", word: "terrible accident" },
  { czWord: "kapsy od kalhot", word: "trouser pockets" },
  {
    czWord: "podle plánu",
    word: "according to the plan, as planned,  as scheduled",
  },
  { czWord: "podle propočtů", word: "according to calculations" },
  { czWord: "oblasti postižené záplavami", word: "areas affected by floods" },
  { czWord: "i když", word: "even when, even though, although" },
  { czWord: "Připadne mi to nespravedlivé.", word: "It appears unfair to me." },
  { czWord: "mladistvý vzhled", word: "youthful appearance" },
  { czWord: "Nepři se se mnou!", word: "Don't argue with me!" },
  { czWord: "domluvit (si) schůzku", word: "arrange a meeting" },
  { czWord: "Zařídím to.", word: "I will arrange it." },
  { czWord: "dohodnout se, že...", word: "make an arrangement that" },
  { czWord: "tvrdě spát, zařezávat", word: "be fast asleep" },
  { czWord: "Spíš?", word: "Are you asleep?" },
  { czWord: "Účastnil se setkání.", word: "He attended the meeting." },
  { czWord: "vařená rýže", word: "boiled rice" },
  { czWord: "bod varu", word: "boiling point" },
  { czWord: "čistý list papíru", word: "blank sheet of paper" },
  { czWord: "čistý formulář nepopsaný", word: "blank form" },
  { czWord: "stinná/světlá stránka čeho", word: "the darker/bright side" },
  { czWord: "oděvní průmysl", word: "clothing industry" },
  { czWord: "několik vrstev oblečení", word: "several layers of clothing" },
  { czWord: "sloupec tabulky", word: "table column" },
  { czWord: "v prostředním sloupci", word: "n the middle column" },
  { czWord: "Soutěží mezi sebou.", word: "They compete with each other." },
  {
    czWord: "konkurenční boj",
    word: "competition, competing, competitive struggle",
  },
  { czWord: "tvůrčí psaní", word: "creative writing" },
  { czWord: "houfy spousty", word: "hordes, crowds, army" },
  { czWord: "diváci, publikum", word: "the crowd" },
  { czWord: "přelidněný, přeplněný", word: "crowded" },
  { czWord: "kudrnatý osoba", word: "curly-haired" },
  { czWord: "cyklistická stezka", word: "cycle track" },
  { czWord: "Objevil novou planetu.", word: "He discovered a new planet." },
  { czWord: "buď ... anebo", word: "either ... or" },
  { czWord: "tak či tak/onak", word: "either way" },
  { czWord: "obrovský, ohromný,", word: "enormous" },
  { czWord: "přesný opak", word: "the exact opposite" },
  { czWord: "právě v tento okamžik", word: "this exact moment" },
  { czWord: "až na to, že,", word: "except that" },
  { czWord: "vyjádřit svůj zármutek", word: "express one's sorrow" },
  { czWord: "vyjádřit hluboké politování", word: "express one's deep regret" },
  { czWord: "bezpečnostní prvky", word: "safety features" },
  { czWord: "(vý)počty", word: "figures" },
  { czWord: "řečnický obrat", word: "figure of speech" },
  { czWord: "jíst příborem", word: "use a knife and fork" },
  { czWord: "Naštěstí se vrátil včas.", word: "Fortunately, he came back on time." },
  { czWord: "pokročit,", word: "go further" },
  { czWord: "bez (dalších) okolků/průtahů", word: "without further/more ado" },
  { czWord: "zabránit dalším škodám", word: "prevent further damage" },
  { czWord: "(mezi)generační propast", word: "generation gap" },
  { czWord: "překlenout propast mezi", word: "bridge the gap between" },
  { czWord: "cena bez/včetně DPH", word: "price excluding/including VAT" },
  { czWord: "To je v ceně. zahrnuto", word: "It's included (in the price)" },
  { czWord: "zaplést se, zapojit se", word: "get involved in" },
  {
    czWord: "Stal se účastníkem dopravní nehody.",
    word: "He was involved in a car accident.",
  },
  { czWord: "účastník nehody", word: "person involved in the accident" },
  { czWord: "ani v nejmenším/trochu", word: "not in the least" },
  { czWord: "v neposlední řadě", word: "last (but) not least" },
  { czWord: "pravděpodobně", word: "likely" },
  { czWord: "pozorný posluchač", word: "attentive listener" },
  { czWord: "nákladní vůz", word: "lorry, truck" },
  { czWord: "Je to nádherné město.", word: "it's a lovely city" },
  { czWord: "Je krásně. o počasí", word: "The weather is lovely." },
  { czWord: "převážná část", word: "major part," },
  { czWord: "mhouřit oči", word: "narrow one's eyes, squint, squinch" },
  { czWord: "úzký, těsný", word: "narrow" },
  { czWord: "ani zdaleka (ne)", word: "not nearly" },
  { czWord: "ořech, oříšek , matice, matka, blázen, fanatik", word: "nut" },
  { czWord: "pec, trouba, kamna", word: "oven" },
  { czWord: "zacházet do detailů", word: "go into particulars" },
  { czWord: "Co konkrétně?", word: "What in particular?" },
  {
    czWord: "Máš na mysli něco konkrétního?",
    word: "Have you anything particular in mind?",
  },
  { czWord: "vzor", word: "pattern" },
  { czWord: "(vy)konat, provést, (u)dělat", word: "perform" },
  { czWord: "možná, třeba, snad nejistota", word: "perhaps" },
  { czWord: "domácí mazlíček", word: "pet" },
  { czWord: "rostlina", word: "plant" },
  { czWord: "talíř, tác, podnos", word: "plate" },
  { czWord: "kapsa", word: "pocket" },
  { czWord: "znečištění atmosféry", word: "atmospheric pollution" },
  { czWord: "znečištění ovzduší", word: "air pollution" },
  { czWord: "Vykulil oči ...", word: "His eyes popped" },
  { czWord: "Existuje spousta možností.", word: "There are lots of possibilities" },
  { czWord: "vyčerpat všechny možnosti", word: "exhaust all possibilities" },
  { czWord: "Předpovědět", word: "Predict" },
  { czWord: "Lze tomu předcházet.", word: "It may be prevented." },
  { czWord: "zamezit šíření nemoci", word: "prevent the spread of the disease" },
  { czWord: "přesný", word: "precise" },
  { czWord: "přesněji řečeno", word: "to be more precise" },
  { czWord: "poskytnout služby", word: "provide services" },
  { czWord: "pro ilustraci, na ukázku", word: "for illustrative purposes" },
  { czWord: "pro léčebné účely", word: "for medicinal purposes" },
  { czWord: "zvýšit hlas při rozčilení ap.", word: "raise one's voice" },
  { czWord: "Raději bych to nedělal.", word: "I'd rather not do that." },
  { czWord: "Než tady čekat, půjdu sám.", word: "I'll go alone rather than wait." },
  { czWord: "nedávné události", word: "recent events" },
  { czWord: "Odkázal mě na Vás.", word: "He referred me to you" },
  { czWord: "odkázat", word: "refer" },
  { czWord: "pravidelně", word: "on a regular basis" },
  { czWord: "v pravidelných intervalech", word: "at regular intervals" },
  { czWord: "ozvat se na inzerát", word: "respond to an advertisement" },
  { czWord: "v reakci na", word: "in response" },
  { czWord: "posoudit situaci", word: "review a situation" },
  { czWord: "zopakovat si slovíčka", word: "review/revise vocabulary" },
  { czWord: "posouzení", word: "review" },
  { czWord: "odpadky", word: "rubbish" },
  { czWord: "kecat nesmysly", word: "talk rubbish" },
  { czWord: "rozvrh, plán", word: "schedule" },
  { czWord: "Čelí několika obviněním.", word: "He faces several charges" },
  { czWord: "několikrát", word: "several times" },
  { czWord: "nepřirozený tvar", word: "unnatural shape" },
  { czWord: "být v dobré kondici", word: "be in good shape" },
  { czWord: "prostěradlo", word: "sheet" },
  { czWord: "místo,plocha", word: "site" },
  { czWord: "vyřešit", word: "solve" },
  { czWord: "objasnit vraždu", word: "solve the murder (case)" },
  {
    czWord: "Právě to řešíme.",
    word: "We are just trying to solve/looking into it",
  },
  { czWord: "třídit", word: "sort" },
  { czWord: "razítko", word: "stamp" },
  { czWord: "stav/stát", word: "state" },
  { czWord: "válečný stav", word: "state of war" },
  {
    czWord: "průzkum (veřejného) mínění, zjišťování názorů",
    word: "(public) opinion survey",
  },
  { czWord: "průzkum", word: "survey" },
  { czWord: "dráha", word: "track" },


];
